// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: arda/workflow/v1/workflow.proto

package workflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessCase struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CaseType           string                 `protobuf:"bytes,3,opt,name=case_type,json=caseType,proto3" json:"case_type,omitempty"`
	CaseCode           string                 `protobuf:"bytes,4,opt,name=case_code,json=caseCode,proto3" json:"case_code,omitempty"`
	Title              string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	PrimaryObjectType  string                 `protobuf:"bytes,6,opt,name=primary_object_type,json=primaryObjectType,proto3" json:"primary_object_type,omitempty"`
	PrimaryObjectId    string                 `protobuf:"bytes,7,opt,name=primary_object_id,json=primaryObjectId,proto3" json:"primary_object_id,omitempty"`
	DomainService      string                 `protobuf:"bytes,8,opt,name=domain_service,json=domainService,proto3" json:"domain_service,omitempty"`
	Status             string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep        string                 `protobuf:"bytes,10,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Priority           string                 `protobuf:"bytes,11,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedBy          string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	AssignedTo         string                 `protobuf:"bytes,13,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	CandidateRole      string                 `protobuf:"bytes,14,opt,name=candidate_role,json=candidateRole,proto3" json:"candidate_role,omitempty"`
	SlaPolicyId        string                 `protobuf:"bytes,15,opt,name=sla_policy_id,json=slaPolicyId,proto3" json:"sla_policy_id,omitempty"`
	SlaDueAt           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=sla_due_at,json=slaDueAt,proto3" json:"sla_due_at,omitempty"`
	ProcessInstanceKey int64                  `protobuf:"varint,17,opt,name=process_instance_key,json=processInstanceKey,proto3" json:"process_instance_key,omitempty"`
	BpmnProcessId      string                 `protobuf:"bytes,18,opt,name=bpmn_process_id,json=bpmnProcessId,proto3" json:"bpmn_process_id,omitempty"`
	BpmnVersion        int32                  `protobuf:"varint,19,opt,name=bpmn_version,json=bpmnVersion,proto3" json:"bpmn_version,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BusinessCase) Reset() {
	*x = BusinessCase{}
	mi := &file_arda_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessCase) ProtoMessage() {}

func (x *BusinessCase) ProtoReflect() protoreflect.Message {
	mi := &file_arda_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessCase.ProtoReflect.Descriptor instead.
func (*BusinessCase) Descriptor() ([]byte, []int) {
	return file_arda_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BusinessCase) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BusinessCase) GetCaseType() string {
	if x != nil {
		return x.CaseType
	}
	return ""
}

func (x *BusinessCase) GetCaseCode() string {
	if x != nil {
		return x.CaseCode
	}
	return ""
}

func (x *BusinessCase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BusinessCase) GetPrimaryObjectType() string {
	if x != nil {
		return x.PrimaryObjectType
	}
	return ""
}

func (x *BusinessCase) GetPrimaryObjectId() string {
	if x != nil {
		return x.PrimaryObjectId
	}
	return ""
}

func (x *BusinessCase) GetDomainService() string {
	if x != nil {
		return x.DomainService
	}
	return ""
}

func (x *BusinessCase) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BusinessCase) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *BusinessCase) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *BusinessCase) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *BusinessCase) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *BusinessCase) GetCandidateRole() string {
	if x != nil {
		return x.CandidateRole
	}
	return ""
}

func (x *BusinessCase) GetSlaPolicyId() string {
	if x != nil {
		return x.SlaPolicyId
	}
	return ""
}

func (x *BusinessCase) GetSlaDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SlaDueAt
	}
	return nil
}

func (x *BusinessCase) GetProcessInstanceKey() int64 {
	if x != nil {
		return x.ProcessInstanceKey
	}
	return 0
}

func (x *BusinessCase) GetBpmnProcessId() string {
	if x != nil {
		return x.BpmnProcessId
	}
	return ""
}

func (x *BusinessCase) GetBpmnVersion() int32 {
	if x != nil {
		return x.BpmnVersion
	}
	return 0
}

func (x *BusinessCase) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BusinessCase) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BusinessCase) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CreateCaseRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CaseType          string                 `protobuf:"bytes,2,opt,name=case_type,json=caseType,proto3" json:"case_type,omitempty"`
	CaseCode          string                 `protobuf:"bytes,3,opt,name=case_code,json=caseCode,proto3" json:"case_code,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	PrimaryObjectType string                 `protobuf:"bytes,5,opt,name=primary_object_type,json=primaryObjectType,proto3" json:"primary_object_type,omitempty"`
	PrimaryObjectId   string                 `protobuf:"bytes,6,opt,name=primary_object_id,json=primaryObjectId,proto3" json:"primary_object_id,omitempty"`
	DomainService     string                 `protobuf:"bytes,7,opt,name=domain_service,json=domainService,proto3" json:"domain_service,omitempty"`
	Priority          string                 `protobuf:"bytes,8,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedBy         string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCaseRequest) Reset() {
	*x = CreateCaseRequest{}
	mi := &file_arda_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaseRequest) ProtoMessage() {}

func (x *CreateCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaseRequest.ProtoReflect.Descriptor instead.
func (*CreateCaseRequest) Descriptor() ([]byte, []int) {
	return file_arda_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCaseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCaseRequest) GetCaseType() string {
	if x != nil {
		return x.CaseType
	}
	return ""
}

func (x *CreateCaseRequest) GetCaseCode() string {
	if x != nil {
		return x.CaseCode
	}
	return ""
}

func (x *CreateCaseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCaseRequest) GetPrimaryObjectType() string {
	if x != nil {
		return x.PrimaryObjectType
	}
	return ""
}

func (x *CreateCaseRequest) GetPrimaryObjectId() string {
	if x != nil {
		return x.PrimaryObjectId
	}
	return ""
}

func (x *CreateCaseRequest) GetDomainService() string {
	if x != nil {
		return x.DomainService
	}
	return ""
}

func (x *CreateCaseRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateCaseRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateCaseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SubmitCaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CaseId         string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Actor          string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Variables      *structpb.Struct       `protobuf:"bytes,3,opt,name=variables,proto3" json:"variables,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitCaseRequest) Reset() {
	*x = SubmitCaseRequest{}
	mi := &file_arda_workflow_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCaseRequest) ProtoMessage() {}

func (x *SubmitCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_workflow_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCaseRequest.ProtoReflect.Descriptor instead.
func (*SubmitCaseRequest) Descriptor() ([]byte, []int) {
	return file_arda_workflow_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *SubmitCaseRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *SubmitCaseRequest) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SubmitCaseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

var File_arda_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_arda_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1farda/workflow/v1/workflow.proto\x12\x10arda.workflow.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x06\n" +
	"\fBusinessCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tcase_type\x18\x03 \x01(\tR\bcaseType\x12\x1b\n" +
	"\tcase_code\x18\x04 \x01(\tR\bcaseCode\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12.\n" +
	"\x13primary_object_type\x18\x06 \x01(\tR\x11primaryObjectType\x12*\n" +
	"\x11primary_object_id\x18\a \x01(\tR\x0fprimaryObjectId\x12%\n" +
	"\x0edomain_service\x18\b \x01(\tR\rdomainService\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\n" +
	" \x01(\tR\vcurrentStep\x12\x1a\n" +
	"\bpriority\x18\v \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\x12\x1f\n" +
	"\vassigned_to\x18\r \x01(\tR\n" +
	"assignedTo\x12%\n" +
	"\x0ecandidate_role\x18\x0e \x01(\tR\rcandidateRole\x12\"\n" +
	"\rsla_policy_id\x18\x0f \x01(\tR\vslaPolicyId\x128\n" +
	"\n" +
	"sla_due_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\bslaDueAt\x120\n" +
	"\x14process_instance_key\x18\x11 \x01(\x03R\x12processInstanceKey\x12&\n" +
	"\x0fbpmn_process_id\x18\x12 \x01(\tR\rbpmnProcessId\x12!\n" +
	"\fbpmn_version\x18\x13 \x01(\x05R\vbpmnVersion\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xe7\x02\n" +
	"\x11CreateCaseRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tcase_type\x18\x02 \x01(\tR\bcaseType\x12\x1b\n" +
	"\tcase_code\x18\x03 \x01(\tR\bcaseCode\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12.\n" +
	"\x13primary_object_type\x18\x05 \x01(\tR\x11primaryObjectType\x12*\n" +
	"\x11primary_object_id\x18\x06 \x01(\tR\x0fprimaryObjectId\x12%\n" +
	"\x0edomain_service\x18\a \x01(\tR\rdomainService\x12\x1a\n" +
	"\bpriority\x18\b \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\"\xa2\x01\n" +
	"\x11SubmitCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x125\n" +
	"\tvariables\x18\x03 \x01(\v2\x17.google.protobuf.StructR\tvariables\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey2\xbe\x01\n" +
	"\x16WorkflowCommandService\x12Q\n" +
	"\n" +
	"CreateCase\x12#.arda.workflow.v1.CreateCaseRequest\x1a\x1e.arda.workflow.v1.BusinessCase\x12Q\n" +
	"\n" +
	"SubmitCase\x12#.arda.workflow.v1.SubmitCaseRequest\x1a\x1e.arda.workflow.v1.BusinessCaseBEZCgithub.com/arda-labs/arda/libs/go/arda-proto/workflow/v1;workflowv1b\x06proto3"

var (
	file_arda_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_arda_workflow_v1_workflow_proto_rawDescData []byte
)

func file_arda_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_arda_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_arda_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arda_workflow_v1_workflow_proto_rawDesc), len(file_arda_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_arda_workflow_v1_workflow_proto_rawDescData
}

var file_arda_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_arda_workflow_v1_workflow_proto_goTypes = []any{
	(*BusinessCase)(nil),          // 0: arda.workflow.v1.BusinessCase
	(*CreateCaseRequest)(nil),     // 1: arda.workflow.v1.CreateCaseRequest
	(*SubmitCaseRequest)(nil),     // 2: arda.workflow.v1.SubmitCaseRequest
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
}
var file_arda_workflow_v1_workflow_proto_depIdxs = []int32{
	3, // 0: arda.workflow.v1.BusinessCase.sla_due_at:type_name -> google.protobuf.Timestamp
	3, // 1: arda.workflow.v1.BusinessCase.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: arda.workflow.v1.BusinessCase.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: arda.workflow.v1.BusinessCase.completed_at:type_name -> google.protobuf.Timestamp
	4, // 4: arda.workflow.v1.SubmitCaseRequest.variables:type_name -> google.protobuf.Struct
	1, // 5: arda.workflow.v1.WorkflowCommandService.CreateCase:input_type -> arda.workflow.v1.CreateCaseRequest
	2, // 6: arda.workflow.v1.WorkflowCommandService.SubmitCase:input_type -> arda.workflow.v1.SubmitCaseRequest
	0, // 7: arda.workflow.v1.WorkflowCommandService.CreateCase:output_type -> arda.workflow.v1.BusinessCase
	0, // 8: arda.workflow.v1.WorkflowCommandService.SubmitCase:output_type -> arda.workflow.v1.BusinessCase
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_arda_workflow_v1_workflow_proto_init() }
func file_arda_workflow_v1_workflow_proto_init() {
	if File_arda_workflow_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arda_workflow_v1_workflow_proto_rawDesc), len(file_arda_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arda_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_arda_workflow_v1_workflow_proto_depIdxs,
		MessageInfos:      file_arda_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_arda_workflow_v1_workflow_proto = out.File
	file_arda_workflow_v1_workflow_proto_goTypes = nil
	file_arda_workflow_v1_workflow_proto_depIdxs = nil
}
