// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: arda/deposit/v1/deposit.proto

package depositv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckSettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavingsCode   string                 `protobuf:"bytes,1,opt,name=savings_code,json=savingsCode,proto3" json:"savings_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSettleRequest) Reset() {
	*x = CheckSettleRequest{}
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSettleRequest) ProtoMessage() {}

func (x *CheckSettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSettleRequest.ProtoReflect.Descriptor instead.
func (*CheckSettleRequest) Descriptor() ([]byte, []int) {
	return file_arda_deposit_v1_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *CheckSettleRequest) GetSavingsCode() string {
	if x != nil {
		return x.SavingsCode
	}
	return ""
}

type CheckSettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSettleResponse) Reset() {
	*x = CheckSettleResponse{}
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSettleResponse) ProtoMessage() {}

func (x *CheckSettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSettleResponse.ProtoReflect.Descriptor instead.
func (*CheckSettleResponse) Descriptor() ([]byte, []int) {
	return file_arda_deposit_v1_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *CheckSettleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckSettleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavingsCode   string                 `protobuf:"bytes,1,opt,name=savings_code,json=savingsCode,proto3" json:"savings_code,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_arda_deposit_v1_deposit_proto_rawDescGZIP(), []int{2}
}

func (x *SettleRequest) GetSavingsCode() string {
	if x != nil {
		return x.SavingsCode
	}
	return ""
}

func (x *SettleRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type SettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleResponse) Reset() {
	*x = SettleResponse{}
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleResponse) ProtoMessage() {}

func (x *SettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_deposit_v1_deposit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleResponse.ProtoReflect.Descriptor instead.
func (*SettleResponse) Descriptor() ([]byte, []int) {
	return file_arda_deposit_v1_deposit_proto_rawDescGZIP(), []int{3}
}

func (x *SettleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_arda_deposit_v1_deposit_proto protoreflect.FileDescriptor

const file_arda_deposit_v1_deposit_proto_rawDesc = "" +
	"\n" +
	"\x1darda/deposit/v1/deposit.proto\x12\x0farda.deposit.v1\"7\n" +
	"\x12CheckSettleRequest\x12!\n" +
	"\fsavings_code\x18\x01 \x01(\tR\vsavingsCode\"?\n" +
	"\x13CheckSettleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\rSettleRequest\x12!\n" +
	"\fsavings_code\x18\x01 \x01(\tR\vsavingsCode\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\" \n" +
	"\x0eSettleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xbc\x01\n" +
	"\x15DepositCommandService\x12X\n" +
	"\vCheckSettle\x12#.arda.deposit.v1.CheckSettleRequest\x1a$.arda.deposit.v1.CheckSettleResponse\x12I\n" +
	"\x06Settle\x12\x1e.arda.deposit.v1.SettleRequest\x1a\x1f.arda.deposit.v1.SettleResponseBCZAgithub.com/arda-labs/arda/libs/go/arda-proto/deposit/v1;depositv1b\x06proto3"

var (
	file_arda_deposit_v1_deposit_proto_rawDescOnce sync.Once
	file_arda_deposit_v1_deposit_proto_rawDescData []byte
)

func file_arda_deposit_v1_deposit_proto_rawDescGZIP() []byte {
	file_arda_deposit_v1_deposit_proto_rawDescOnce.Do(func() {
		file_arda_deposit_v1_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arda_deposit_v1_deposit_proto_rawDesc), len(file_arda_deposit_v1_deposit_proto_rawDesc)))
	})
	return file_arda_deposit_v1_deposit_proto_rawDescData
}

var file_arda_deposit_v1_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_arda_deposit_v1_deposit_proto_goTypes = []any{
	(*CheckSettleRequest)(nil),  // 0: arda.deposit.v1.CheckSettleRequest
	(*CheckSettleResponse)(nil), // 1: arda.deposit.v1.CheckSettleResponse
	(*SettleRequest)(nil),       // 2: arda.deposit.v1.SettleRequest
	(*SettleResponse)(nil),      // 3: arda.deposit.v1.SettleResponse
}
var file_arda_deposit_v1_deposit_proto_depIdxs = []int32{
	0, // 0: arda.deposit.v1.DepositCommandService.CheckSettle:input_type -> arda.deposit.v1.CheckSettleRequest
	2, // 1: arda.deposit.v1.DepositCommandService.Settle:input_type -> arda.deposit.v1.SettleRequest
	1, // 2: arda.deposit.v1.DepositCommandService.CheckSettle:output_type -> arda.deposit.v1.CheckSettleResponse
	3, // 3: arda.deposit.v1.DepositCommandService.Settle:output_type -> arda.deposit.v1.SettleResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arda_deposit_v1_deposit_proto_init() }
func file_arda_deposit_v1_deposit_proto_init() {
	if File_arda_deposit_v1_deposit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arda_deposit_v1_deposit_proto_rawDesc), len(file_arda_deposit_v1_deposit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arda_deposit_v1_deposit_proto_goTypes,
		DependencyIndexes: file_arda_deposit_v1_deposit_proto_depIdxs,
		MessageInfos:      file_arda_deposit_v1_deposit_proto_msgTypes,
	}.Build()
	File_arda_deposit_v1_deposit_proto = out.File
	file_arda_deposit_v1_deposit_proto_goTypes = nil
	file_arda_deposit_v1_deposit_proto_depIdxs = nil
}
