apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: arda
  namespace: argocd
spec:
  description: Arda applications
  sourceRepos:
    - https://github.com/arda-labs/arda-be.git
    - https://github.com/arda-labs/arda-fe.git
  destinations:
    - namespace: arda-app
      server: https://kubernetes.default.svc
    - namespace: arda-web
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
