// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: arda/crm/v1/member.proto

package crmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemberCommandService_CheckMemberRequest_FullMethodName   = "/arda.crm.v1.MemberCommandService/CheckMemberRequest"
	MemberCommandService_ResolveMemberRequest_FullMethodName = "/arda.crm.v1.MemberCommandService/ResolveMemberRequest"
)

// MemberCommandServiceClient is the client API for MemberCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemberCommandService is the callback surface workflow-service workers use for
// the CRM_MEMBER_V1 flow (QTDND membership capital movements live in
// crm-service). Tenant scope arrives via gRPC metadata.
type MemberCommandServiceClient interface {
	// CheckMemberRequest re-reads the staged capital request and reports whether
	// the checker may approve it (member active, withdrawal within the stake).
	CheckMemberRequest(ctx context.Context, in *CheckMemberRequestRequest, opts ...grpc.CallOption) (*CheckMemberRequestResponse, error)
	// ResolveMemberRequest records the checker decision; APPROVE moves the stake
	// and marks the request APPROVED in one transaction.
	ResolveMemberRequest(ctx context.Context, in *ResolveMemberRequestRequest, opts ...grpc.CallOption) (*ResolveMemberRequestResponse, error)
}

type memberCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberCommandServiceClient(cc grpc.ClientConnInterface) MemberCommandServiceClient {
	return &memberCommandServiceClient{cc}
}

func (c *memberCommandServiceClient) CheckMemberRequest(ctx context.Context, in *CheckMemberRequestRequest, opts ...grpc.CallOption) (*CheckMemberRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMemberRequestResponse)
	err := c.cc.Invoke(ctx, MemberCommandService_CheckMemberRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberCommandServiceClient) ResolveMemberRequest(ctx context.Context, in *ResolveMemberRequestRequest, opts ...grpc.CallOption) (*ResolveMemberRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveMemberRequestResponse)
	err := c.cc.Invoke(ctx, MemberCommandService_ResolveMemberRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberCommandServiceServer is the server API for MemberCommandService service.
// All implementations must embed UnimplementedMemberCommandServiceServer
// for forward compatibility.
//
// MemberCommandService is the callback surface workflow-service workers use for
// the CRM_MEMBER_V1 flow (QTDND membership capital movements live in
// crm-service). Tenant scope arrives via gRPC metadata.
type MemberCommandServiceServer interface {
	// CheckMemberRequest re-reads the staged capital request and reports whether
	// the checker may approve it (member active, withdrawal within the stake).
	CheckMemberRequest(context.Context, *CheckMemberRequestRequest) (*CheckMemberRequestResponse, error)
	// ResolveMemberRequest records the checker decision; APPROVE moves the stake
	// and marks the request APPROVED in one transaction.
	ResolveMemberRequest(context.Context, *ResolveMemberRequestRequest) (*ResolveMemberRequestResponse, error)
	mustEmbedUnimplementedMemberCommandServiceServer()
}

// UnimplementedMemberCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberCommandServiceServer struct{}

func (UnimplementedMemberCommandServiceServer) CheckMemberRequest(context.Context, *CheckMemberRequestRequest) (*CheckMemberRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMemberRequest not implemented")
}
func (UnimplementedMemberCommandServiceServer) ResolveMemberRequest(context.Context, *ResolveMemberRequestRequest) (*ResolveMemberRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveMemberRequest not implemented")
}
func (UnimplementedMemberCommandServiceServer) mustEmbedUnimplementedMemberCommandServiceServer() {}
func (UnimplementedMemberCommandServiceServer) testEmbeddedByValue()                              {}

// UnsafeMemberCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberCommandServiceServer will
// result in compilation errors.
type UnsafeMemberCommandServiceServer interface {
	mustEmbedUnimplementedMemberCommandServiceServer()
}

func RegisterMemberCommandServiceServer(s grpc.ServiceRegistrar, srv MemberCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedMemberCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemberCommandService_ServiceDesc, srv)
}

func _MemberCommandService_CheckMemberRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMemberRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberCommandServiceServer).CheckMemberRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberCommandService_CheckMemberRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberCommandServiceServer).CheckMemberRequest(ctx, req.(*CheckMemberRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberCommandService_ResolveMemberRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveMemberRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberCommandServiceServer).ResolveMemberRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberCommandService_ResolveMemberRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberCommandServiceServer).ResolveMemberRequest(ctx, req.(*ResolveMemberRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemberCommandService_ServiceDesc is the grpc.ServiceDesc for MemberCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemberCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arda.crm.v1.MemberCommandService",
	HandlerType: (*MemberCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckMemberRequest",
			Handler:    _MemberCommandService_CheckMemberRequest_Handler,
		},
		{
			MethodName: "ResolveMemberRequest",
			Handler:    _MemberCommandService_ResolveMemberRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arda/crm/v1/member.proto",
}
