app_name: auth-gateway
http_addr: 0.0.0.0:8082
log_level: debug
token_strategy: jwks

jwt_secret: ""
jwt_issuer: "https://auth.arda.io.vn"
jwt_audience: arda-api
jwks_url: "https://auth.arda.io.vn/.well-known/jwks.json"

introspection_url: "http://192.168.100.201:30445/oauth2/introspect"
introspection_client_id: auth-gateway
introspection_client_secret: auth-gateway-secret

iam_service_url: "http://localhost:8080"
iam_context_cache_ttl_seconds: 60
platform_service_url: "http://localhost:8091"
finance_service_url: "http://localhost:8090"
media_service_url: "http://localhost:8092"
workflow_service_url: "http://localhost:8093"
crm_service_url: "http://localhost:8094"
hrm_service_url: "http://localhost:8097"
notification_service_url: "http://localhost:8095"
mdm_service_url: "http://localhost:8096"
proxy_backend_url: "http://localhost:8080"
policy_file: "configs/policy.yaml"

kratos_public_url: "https://identity.arda.io.vn"
hydra_admin_url: "http://192.168.100.201:30445"
hydra_public_url: "https://auth.arda.io.vn"
oauth_client_id: "arda-shell"
oauth_redirect_uri: "http://localhost:5000/api/auth/callback"
oauth_redirect_uris: "https://arda.io.vn/api/auth/callback,https://arda.io.vn/callback,http://localhost:5000/api/auth/callback,http://localhost:5000/callback"

redis_url: "redis://default:Pkz1%2F8t3mVkXZKt%2F4IBg3U3nqtzFYZs%2FK%2Fvhnt0C6C4%3D@192.168.100.201:30379"
session_cookie_name: arda_sid
session_cookie_domain: ""
session_ttl_seconds: 86400
recent_auth_window_seconds: 300
cookie_secure: false
cookie_same_site: Lax
