resources:
  - auth-gateway.yaml
  - iam-service.yaml
  - platform-service.yaml
  - finance-service.yaml
  - media-service.yaml
  - workflow-service.yaml
  - crm-service.yaml
  - notification-service.yaml
