// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: arda/media/v1/media.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicIds     []string               `protobuf:"bytes,1,rep,name=public_ids,json=publicIds,proto3" json:"public_ids,omitempty"`
	OwnerType     string                 `protobuf:"bytes,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachFilesRequest) Reset() {
	*x = AttachFilesRequest{}
	mi := &file_arda_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachFilesRequest) ProtoMessage() {}

func (x *AttachFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachFilesRequest.ProtoReflect.Descriptor instead.
func (*AttachFilesRequest) Descriptor() ([]byte, []int) {
	return file_arda_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *AttachFilesRequest) GetPublicIds() []string {
	if x != nil {
		return x.PublicIds
	}
	return nil
}

func (x *AttachFilesRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *AttachFilesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type AttachFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachFilesResponse) Reset() {
	*x = AttachFilesResponse{}
	mi := &file_arda_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachFilesResponse) ProtoMessage() {}

func (x *AttachFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachFilesResponse.ProtoReflect.Descriptor instead.
func (*AttachFilesResponse) Descriptor() ([]byte, []int) {
	return file_arda_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *AttachFilesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_arda_media_v1_media_proto protoreflect.FileDescriptor

const file_arda_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x19arda/media/v1/media.proto\x12\rarda.media.v1\"m\n" +
	"\x12AttachFilesRequest\x12\x1d\n" +
	"\n" +
	"public_ids\x18\x01 \x03(\tR\tpublicIds\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\"%\n" +
	"\x13AttachFilesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2d\n" +
	"\fMediaService\x12T\n" +
	"\vAttachFiles\x12!.arda.media.v1.AttachFilesRequest\x1a\".arda.media.v1.AttachFilesResponseB?Z=github.com/arda-labs/arda/libs/go/arda-proto/media/v1;mediav1b\x06proto3"

var (
	file_arda_media_v1_media_proto_rawDescOnce sync.Once
	file_arda_media_v1_media_proto_rawDescData []byte
)

func file_arda_media_v1_media_proto_rawDescGZIP() []byte {
	file_arda_media_v1_media_proto_rawDescOnce.Do(func() {
		file_arda_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arda_media_v1_media_proto_rawDesc), len(file_arda_media_v1_media_proto_rawDesc)))
	})
	return file_arda_media_v1_media_proto_rawDescData
}

var file_arda_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arda_media_v1_media_proto_goTypes = []any{
	(*AttachFilesRequest)(nil),  // 0: arda.media.v1.AttachFilesRequest
	(*AttachFilesResponse)(nil), // 1: arda.media.v1.AttachFilesResponse
}
var file_arda_media_v1_media_proto_depIdxs = []int32{
	0, // 0: arda.media.v1.MediaService.AttachFiles:input_type -> arda.media.v1.AttachFilesRequest
	1, // 1: arda.media.v1.MediaService.AttachFiles:output_type -> arda.media.v1.AttachFilesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arda_media_v1_media_proto_init() }
func file_arda_media_v1_media_proto_init() {
	if File_arda_media_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arda_media_v1_media_proto_rawDesc), len(file_arda_media_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arda_media_v1_media_proto_goTypes,
		DependencyIndexes: file_arda_media_v1_media_proto_depIdxs,
		MessageInfos:      file_arda_media_v1_media_proto_msgTypes,
	}.Build()
	File_arda_media_v1_media_proto = out.File
	file_arda_media_v1_media_proto_goTypes = nil
	file_arda_media_v1_media_proto_depIdxs = nil
}
