// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: arda/notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SourceService  string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	SourceEventId  string                 `protobuf:"bytes,4,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	EventType      string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TemplateKey    string                 `protobuf:"bytes,6,opt,name=template_key,json=templateKey,proto3" json:"template_key,omitempty"`
	Channels       []string               `protobuf:"bytes,7,rep,name=channels,proto3" json:"channels,omitempty"`
	RecipientsJson string                 `protobuf:"bytes,8,opt,name=recipients_json,json=recipientsJson,proto3" json:"recipients_json,omitempty"`
	PayloadJson    string                 `protobuf:"bytes,9,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,10,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Priority       int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	Type           string                 `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	TitleKey       string                 `protobuf:"bytes,13,opt,name=title_key,json=titleKey,proto3" json:"title_key,omitempty"`
	BodyKey        string                 `protobuf:"bytes,14,opt,name=body_key,json=bodyKey,proto3" json:"body_key,omitempty"`
	Href           string                 `protobuf:"bytes,15,opt,name=href,proto3" json:"href,omitempty"`
	ParamsJson     string                 `protobuf:"bytes,16,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptNotificationRequest) Reset() {
	*x = AcceptNotificationRequest{}
	mi := &file_arda_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNotificationRequest) ProtoMessage() {}

func (x *AcceptNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNotificationRequest.ProtoReflect.Descriptor instead.
func (*AcceptNotificationRequest) Descriptor() ([]byte, []int) {
	return file_arda_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptNotificationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AcceptNotificationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *AcceptNotificationRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *AcceptNotificationRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *AcceptNotificationRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AcceptNotificationRequest) GetTemplateKey() string {
	if x != nil {
		return x.TemplateKey
	}
	return ""
}

func (x *AcceptNotificationRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *AcceptNotificationRequest) GetRecipientsJson() string {
	if x != nil {
		return x.RecipientsJson
	}
	return ""
}

func (x *AcceptNotificationRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *AcceptNotificationRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AcceptNotificationRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AcceptNotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AcceptNotificationRequest) GetTitleKey() string {
	if x != nil {
		return x.TitleKey
	}
	return ""
}

func (x *AcceptNotificationRequest) GetBodyKey() string {
	if x != nil {
		return x.BodyKey
	}
	return ""
}

func (x *AcceptNotificationRequest) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *AcceptNotificationRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type AcceptNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptNotificationResponse) Reset() {
	*x = AcceptNotificationResponse{}
	mi := &file_arda_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNotificationResponse) ProtoMessage() {}

func (x *AcceptNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNotificationResponse.ProtoReflect.Descriptor instead.
func (*AcceptNotificationResponse) Descriptor() ([]byte, []int) {
	return file_arda_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *AcceptNotificationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_arda_notification_v1_notification_proto protoreflect.FileDescriptor

const file_arda_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"'arda/notification/v1/notification.proto\x12\x14arda.notification.v1\"\x9e\x04\n" +
	"\x19AcceptNotificationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\x12&\n" +
	"\x0fsource_event_id\x18\x04 \x01(\tR\rsourceEventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12!\n" +
	"\ftemplate_key\x18\x06 \x01(\tR\vtemplateKey\x12\x1a\n" +
	"\bchannels\x18\a \x03(\tR\bchannels\x12'\n" +
	"\x0frecipients_json\x18\b \x01(\tR\x0erecipientsJson\x12!\n" +
	"\fpayload_json\x18\t \x01(\tR\vpayloadJson\x12%\n" +
	"\x0ecorrelation_id\x18\n" +
	" \x01(\tR\rcorrelationId\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\x12\x1b\n" +
	"\ttitle_key\x18\r \x01(\tR\btitleKey\x12\x19\n" +
	"\bbody_key\x18\x0e \x01(\tR\abodyKey\x12\x12\n" +
	"\x04href\x18\x0f \x01(\tR\x04href\x12\x1f\n" +
	"\vparams_json\x18\x10 \x01(\tR\n" +
	"paramsJson\"]\n" +
	"\x1aAcceptNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x8e\x01\n" +
	"\x13NotificationService\x12w\n" +
	"\x12AcceptNotification\x12/.arda.notification.v1.AcceptNotificationRequest\x1a0.arda.notification.v1.AcceptNotificationResponseBMZKgithub.com/arda-labs/arda/libs/go/arda-proto/notification/v1;notificationv1b\x06proto3"

var (
	file_arda_notification_v1_notification_proto_rawDescOnce sync.Once
	file_arda_notification_v1_notification_proto_rawDescData []byte
)

func file_arda_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_arda_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_arda_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arda_notification_v1_notification_proto_rawDesc), len(file_arda_notification_v1_notification_proto_rawDesc)))
	})
	return file_arda_notification_v1_notification_proto_rawDescData
}

var file_arda_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arda_notification_v1_notification_proto_goTypes = []any{
	(*AcceptNotificationRequest)(nil),  // 0: arda.notification.v1.AcceptNotificationRequest
	(*AcceptNotificationResponse)(nil), // 1: arda.notification.v1.AcceptNotificationResponse
}
var file_arda_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: arda.notification.v1.NotificationService.AcceptNotification:input_type -> arda.notification.v1.AcceptNotificationRequest
	1, // 1: arda.notification.v1.NotificationService.AcceptNotification:output_type -> arda.notification.v1.AcceptNotificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arda_notification_v1_notification_proto_init() }
func file_arda_notification_v1_notification_proto_init() {
	if File_arda_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arda_notification_v1_notification_proto_rawDesc), len(file_arda_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arda_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_arda_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_arda_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_arda_notification_v1_notification_proto = out.File
	file_arda_notification_v1_notification_proto_goTypes = nil
	file_arda_notification_v1_notification_proto_depIdxs = nil
}
