// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: arda/finance/v1/posting.proto

package financev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostingService_ValidatePosting_FullMethodName    = "/arda.finance.v1.PostingService/ValidatePosting"
	PostingService_PostTransaction_FullMethodName    = "/arda.finance.v1.PostingService/PostTransaction"
	PostingService_ReservePosting_FullMethodName     = "/arda.finance.v1.PostingService/ReservePosting"
	PostingService_ReleasePosting_FullMethodName     = "/arda.finance.v1.PostingService/ReleasePosting"
	PostingService_ReverseTransaction_FullMethodName = "/arda.finance.v1.PostingService/ReverseTransaction"
	PostingService_GetJournalEntry_FullMethodName    = "/arda.finance.v1.PostingService/GetJournalEntry"
	PostingService_ListPostingRules_FullMethodName   = "/arda.finance.v1.PostingService/ListPostingRules"
)

// PostingServiceClient is the client API for PostingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PostingService is the single journal-entry gate for all Arda domains
// (docs/accounting-posting-contract.md v0.3 + P1b v2 two-phase balance,
// docs/epas-survey/disbursement-flow-deep-dive.md). Only workflow-service
// workers (and finance itself for internal flows like opening balances and
// cash) call it. Money crosses as int64 minor units; accounts are resolved
// from analytics via fin_acc_class_coa_maps at the accounting_date's COA
// version.
//
// Lifecycle (contract §4): Reserve creates a PENDING entry and holds the
// amounts on fin_account_balances (reserved_*); Post moves the hold to
// posted_* and stamps the entry POSTED; Release frees the hold and stamps
// the entry VOID. Direct posts (accrual/provision/cash/...) skip the hold —
// PostTransaction on a request without a PENDING twin books straight to
// posted_*.
type PostingServiceClient interface {
	// Validate resolves accounts and reports per-line results without writing.
	ValidatePosting(ctx context.Context, in *PostingRequest, opts ...grpc.CallOption) (*ValidationResult, error)
	// PostTransaction writes one balanced journal entry (direct posts book
	// POSTED; a request matching an existing PENDING entry — same tenant +
	// idempotency key — moves that entry's hold to posted instead).
	// Idempotent by (tenant_id, idempotency_key); replays return the original
	// response.
	PostTransaction(ctx context.Context, in *PostingRequest, opts ...grpc.CallOption) (*PostingResponse, error)
	// ReservePosting creates the PENDING entry and holds its amounts
	// (available-balance reservation for approval flows). Idempotent by
	// (tenant_id, idempotency_key).
	ReservePosting(ctx context.Context, in *PostingRequest, opts ...grpc.CallOption) (*PostingResponse, error)
	// ReleasePosting frees the reserved amounts of a PENDING entry and stamps
	// it VOID (the maker-checker reject path).
	ReleasePosting(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*PostingResponse, error)
	// ReverseTransaction creates a reversal entry; the original is immutable.
	ReverseTransaction(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*PostingResponse, error)
	// GetJournalEntry reads one entry (header + lines) by entry_no for the
	// accountant cancellation flow: the workflow init/validate steps guard on
	// its status and reversed_by_entry_id before reversing. Only POSTED and
	// REVERSED entries are readable; anything else is NOT_FOUND.
	GetJournalEntry(ctx context.Context, in *GetJournalEntryRequest, opts ...grpc.CallOption) (*JournalEntryDetail, error)
	// ListPostingRules exposes the fin_accounting_rules card for one document
	// type so workflow workers build their posting lines from config instead of
	// hardcoded classification strings. Unseeded document types return an
	// empty rule list (workers fall back to their built-in legs).
	ListPostingRules(ctx context.Context, in *ListPostingRulesRequest, opts ...grpc.CallOption) (*ListPostingRulesResponse, error)
}

type postingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostingServiceClient(cc grpc.ClientConnInterface) PostingServiceClient {
	return &postingServiceClient{cc}
}

func (c *postingServiceClient) ValidatePosting(ctx context.Context, in *PostingRequest, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, PostingService_ValidatePosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postingServiceClient) PostTransaction(ctx context.Context, in *PostingRequest, opts ...grpc.CallOption) (*PostingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostingResponse)
	err := c.cc.Invoke(ctx, PostingService_PostTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postingServiceClient) ReservePosting(ctx context.Context, in *PostingRequest, opts ...grpc.CallOption) (*PostingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostingResponse)
	err := c.cc.Invoke(ctx, PostingService_ReservePosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postingServiceClient) ReleasePosting(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*PostingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostingResponse)
	err := c.cc.Invoke(ctx, PostingService_ReleasePosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postingServiceClient) ReverseTransaction(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*PostingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostingResponse)
	err := c.cc.Invoke(ctx, PostingService_ReverseTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postingServiceClient) GetJournalEntry(ctx context.Context, in *GetJournalEntryRequest, opts ...grpc.CallOption) (*JournalEntryDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JournalEntryDetail)
	err := c.cc.Invoke(ctx, PostingService_GetJournalEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postingServiceClient) ListPostingRules(ctx context.Context, in *ListPostingRulesRequest, opts ...grpc.CallOption) (*ListPostingRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPostingRulesResponse)
	err := c.cc.Invoke(ctx, PostingService_ListPostingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostingServiceServer is the server API for PostingService service.
// All implementations must embed UnimplementedPostingServiceServer
// for forward compatibility.
//
// PostingService is the single journal-entry gate for all Arda domains
// (docs/accounting-posting-contract.md v0.3 + P1b v2 two-phase balance,
// docs/epas-survey/disbursement-flow-deep-dive.md). Only workflow-service
// workers (and finance itself for internal flows like opening balances and
// cash) call it. Money crosses as int64 minor units; accounts are resolved
// from analytics via fin_acc_class_coa_maps at the accounting_date's COA
// version.
//
// Lifecycle (contract §4): Reserve creates a PENDING entry and holds the
// amounts on fin_account_balances (reserved_*); Post moves the hold to
// posted_* and stamps the entry POSTED; Release frees the hold and stamps
// the entry VOID. Direct posts (accrual/provision/cash/...) skip the hold —
// PostTransaction on a request without a PENDING twin books straight to
// posted_*.
type PostingServiceServer interface {
	// Validate resolves accounts and reports per-line results without writing.
	ValidatePosting(context.Context, *PostingRequest) (*ValidationResult, error)
	// PostTransaction writes one balanced journal entry (direct posts book
	// POSTED; a request matching an existing PENDING entry — same tenant +
	// idempotency key — moves that entry's hold to posted instead).
	// Idempotent by (tenant_id, idempotency_key); replays return the original
	// response.
	PostTransaction(context.Context, *PostingRequest) (*PostingResponse, error)
	// ReservePosting creates the PENDING entry and holds its amounts
	// (available-balance reservation for approval flows). Idempotent by
	// (tenant_id, idempotency_key).
	ReservePosting(context.Context, *PostingRequest) (*PostingResponse, error)
	// ReleasePosting frees the reserved amounts of a PENDING entry and stamps
	// it VOID (the maker-checker reject path).
	ReleasePosting(context.Context, *ReleaseRequest) (*PostingResponse, error)
	// ReverseTransaction creates a reversal entry; the original is immutable.
	ReverseTransaction(context.Context, *ReverseRequest) (*PostingResponse, error)
	// GetJournalEntry reads one entry (header + lines) by entry_no for the
	// accountant cancellation flow: the workflow init/validate steps guard on
	// its status and reversed_by_entry_id before reversing. Only POSTED and
	// REVERSED entries are readable; anything else is NOT_FOUND.
	GetJournalEntry(context.Context, *GetJournalEntryRequest) (*JournalEntryDetail, error)
	// ListPostingRules exposes the fin_accounting_rules card for one document
	// type so workflow workers build their posting lines from config instead of
	// hardcoded classification strings. Unseeded document types return an
	// empty rule list (workers fall back to their built-in legs).
	ListPostingRules(context.Context, *ListPostingRulesRequest) (*ListPostingRulesResponse, error)
	mustEmbedUnimplementedPostingServiceServer()
}

// UnimplementedPostingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostingServiceServer struct{}

func (UnimplementedPostingServiceServer) ValidatePosting(context.Context, *PostingRequest) (*ValidationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePosting not implemented")
}
func (UnimplementedPostingServiceServer) PostTransaction(context.Context, *PostingRequest) (*PostingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostTransaction not implemented")
}
func (UnimplementedPostingServiceServer) ReservePosting(context.Context, *PostingRequest) (*PostingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReservePosting not implemented")
}
func (UnimplementedPostingServiceServer) ReleasePosting(context.Context, *ReleaseRequest) (*PostingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleasePosting not implemented")
}
func (UnimplementedPostingServiceServer) ReverseTransaction(context.Context, *ReverseRequest) (*PostingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseTransaction not implemented")
}
func (UnimplementedPostingServiceServer) GetJournalEntry(context.Context, *GetJournalEntryRequest) (*JournalEntryDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJournalEntry not implemented")
}
func (UnimplementedPostingServiceServer) ListPostingRules(context.Context, *ListPostingRulesRequest) (*ListPostingRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPostingRules not implemented")
}
func (UnimplementedPostingServiceServer) mustEmbedUnimplementedPostingServiceServer() {}
func (UnimplementedPostingServiceServer) testEmbeddedByValue()                        {}

// UnsafePostingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostingServiceServer will
// result in compilation errors.
type UnsafePostingServiceServer interface {
	mustEmbedUnimplementedPostingServiceServer()
}

func RegisterPostingServiceServer(s grpc.ServiceRegistrar, srv PostingServiceServer) {
	// If the following call panics, it indicates UnimplementedPostingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostingService_ServiceDesc, srv)
}

func _PostingService_ValidatePosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostingServiceServer).ValidatePosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostingService_ValidatePosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostingServiceServer).ValidatePosting(ctx, req.(*PostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostingService_PostTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostingServiceServer).PostTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostingService_PostTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostingServiceServer).PostTransaction(ctx, req.(*PostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostingService_ReservePosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostingServiceServer).ReservePosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostingService_ReservePosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostingServiceServer).ReservePosting(ctx, req.(*PostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostingService_ReleasePosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostingServiceServer).ReleasePosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostingService_ReleasePosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostingServiceServer).ReleasePosting(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostingService_ReverseTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostingServiceServer).ReverseTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostingService_ReverseTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostingServiceServer).ReverseTransaction(ctx, req.(*ReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostingService_GetJournalEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJournalEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostingServiceServer).GetJournalEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostingService_GetJournalEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostingServiceServer).GetJournalEntry(ctx, req.(*GetJournalEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostingService_ListPostingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostingServiceServer).ListPostingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostingService_ListPostingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostingServiceServer).ListPostingRules(ctx, req.(*ListPostingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostingService_ServiceDesc is the grpc.ServiceDesc for PostingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arda.finance.v1.PostingService",
	HandlerType: (*PostingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatePosting",
			Handler:    _PostingService_ValidatePosting_Handler,
		},
		{
			MethodName: "PostTransaction",
			Handler:    _PostingService_PostTransaction_Handler,
		},
		{
			MethodName: "ReservePosting",
			Handler:    _PostingService_ReservePosting_Handler,
		},
		{
			MethodName: "ReleasePosting",
			Handler:    _PostingService_ReleasePosting_Handler,
		},
		{
			MethodName: "ReverseTransaction",
			Handler:    _PostingService_ReverseTransaction_Handler,
		},
		{
			MethodName: "GetJournalEntry",
			Handler:    _PostingService_GetJournalEntry_Handler,
		},
		{
			MethodName: "ListPostingRules",
			Handler:    _PostingService_ListPostingRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arda/finance/v1/posting.proto",
}
