package indicator

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// TestGenerateAccountingSeed is an opt-in generator, not a unit test. Run
//
//	GEN_ACCOUNTING_SEED=1 go test ./internal/indicator -run TestGenerateAccountingSeed
//
// to rewrite the seed migration from the catalog fixture when the parser or the
// catalog changes. It is skipped by default so CI never writes files, and the
// committed migration is reviewed like any other.
//
// It is NOT currently enabled: the PCF formulas reference the QTDND regulatory
// chart of accounts (Thông tư 31: TK 10 cash, TK 13 interbank, TK 21 loans),
// while the pilot books post to a Thông tư 92 chart (fin_coa_accounts:
// 1011/1131/1311/1321/…). Matching the two by prefix silently mis-buckets money
// — "13…" would pull customer loans into "Tiền gửi tại TCTD khác". The seed
// must wait for an explicit, accountant-reviewed mapping from each PCF account
// reference to a fin_coa_accounts code; only then is this generator safe to run
// and commit.
func TestGenerateAccountingSeed(t *testing.T) {
	if os.Getenv("GEN_ACCOUNTING_SEED") != "1" {
		t.Skip("set GEN_ACCOUNTING_SEED=1 to regenerate the seed migration")
	}
	blob, err := os.ReadFile(filepath.Join("testdata", "account_formulas.json"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var rows []catalogFormula
	if err := json.Unmarshal(blob, &rows); err != nil {
		t.Fatalf("decode fixture: %v", err)
	}

	type seeded struct {
		code, name, formulaJSON string
		prefixCount             int
	}
	out := []seeded{}
	rejected := []string{}
	for _, row := range rows {
		ab, err := ParseAccountFormula(row.Formula)
		if err != nil {
			rejected = append(rejected, row.Code)
			continue
		}
		if err := ab.validate(); err != nil {
			rejected = append(rejected, row.Code)
			continue
		}
		blob, err := json.Marshal(map[string]any{"type": "account_balance", "accounts": ab})
		if err != nil {
			t.Fatalf("marshal %s: %v", row.Code, err)
		}
		out = append(out, seeded{code: row.Code, name: row.Name, formulaJSON: string(blob), prefixCount: countPrefixes(ab)})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].code < out[j].code })

	var b strings.Builder
	b.WriteString("-- +goose Up\n\n")
	b.WriteString("-- GENERATED by internal/indicator TestGenerateAccountingSeed — edit the parser,\n")
	b.WriteString("-- then regenerate; do not hand-edit the values below.\n")
	b.WriteString("--\n")
	b.WriteString(fmt.Sprintf("-- Seeds the %d PCF accounting indicators whose formulas parse into the\n", len(out)))
	b.WriteString("-- account_balance aggregate. The remaining catalog rows are either descriptive,\n")
	b.WriteString("-- ratios (need the ratio type), or ambiguous conditionals; they are intentionally\n")
	b.WriteString("-- left out until they can be derived without guessing.\n\n")
	b.WriteString("INSERT INTO rpt_indicators\n")
	b.WriteString("    (tenant_id, code, name, unit, group_code, created_by,\n")
	b.WriteString("     kpi_type, periodicity, is_ratio, root_code, root_name, meaning,\n")
	b.WriteString("     sources, formula, dimensions, display_format, rounding_digits)\nVALUES\n")
	for i, row := range out {
		comma := ","
		if i == len(out)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf(
			"    ('00000000-0000-0000-0000-000000000010', '%s', %s, 'VND', 'Tài chính kế toán', 'seed',\n"+
				"     'P', 'D', false, '%s', %s,\n"+
				"     '',\n"+
				"     '[\"rpt_fact_trial_balance_daily\"]',\n"+
				"     '%s',\n"+
				"     '[\"org\",\"time\"]', 'amount', 2)%s\n",
			row.code, sqlStr(row.name), rootOf(row.code), sqlStr(row.name),
			strings.ReplaceAll(row.formulaJSON, "'", "''"), comma))
	}
	b.WriteString("ON CONFLICT (tenant_id, code) DO UPDATE SET\n")
	b.WriteString("    name = EXCLUDED.name, group_code = EXCLUDED.group_code,\n")
	b.WriteString("    sources = EXCLUDED.sources, formula = EXCLUDED.formula,\n")
	b.WriteString("    display_format = EXCLUDED.display_format, updated_at = now();\n\n")
	b.WriteString("-- +goose Down\n")
	b.WriteString("DELETE FROM rpt_indicators\n")
	b.WriteString("WHERE tenant_id = '00000000-0000-0000-0000-000000000010'\n")
	b.WriteString("  AND group_code = 'Tài chính kế toán';\n")

	dest := filepath.Join("..", "..", "migrations", "20260922210000_rpt_accounting_indicator_seeds.sql")
	if err := os.WriteFile(dest, []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write %s: %v", dest, err)
	}
	t.Logf("wrote %d seeded indicators (%d rejected) to %s", len(out), len(rejected), dest)
}

func countPrefixes(ab accountBalance) int {
	n := 0
	for _, t := range ab.Terms {
		n += len(t.Prefixes)
	}
	return n
}

func sqlStr(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

func rootOf(code string) string {
	if i := strings.Index(code, "."); i > 0 {
		return code[:i]
	}
	return code
}
