version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/iam-service ./cmd/iam-service

  run:
    cmds:
      - go run ./cmd/iam-service

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - go vet ./...

  docker:
    cmds:
      - docker build -t iam-service:latest .
