// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: arda/loan/v1/loan.proto

package loanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanCommandService_UpdateContractStatus_FullMethodName         = "/arda.loan.v1.LoanCommandService/UpdateContractStatus"
	LoanCommandService_CheckAdjustment_FullMethodName              = "/arda.loan.v1.LoanCommandService/CheckAdjustment"
	LoanCommandService_ResolveAdjustment_FullMethodName            = "/arda.loan.v1.LoanCommandService/ResolveAdjustment"
	LoanCommandService_CheckDisbursement_FullMethodName            = "/arda.loan.v1.LoanCommandService/CheckDisbursement"
	LoanCommandService_GetDisbursementPostingDetail_FullMethodName = "/arda.loan.v1.LoanCommandService/GetDisbursementPostingDetail"
	LoanCommandService_SettleDisbursement_FullMethodName           = "/arda.loan.v1.LoanCommandService/SettleDisbursement"
	LoanCommandService_ResolveDisbursement_FullMethodName          = "/arda.loan.v1.LoanCommandService/ResolveDisbursement"
)

// LoanCommandServiceClient is the client API for LoanCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LoanCommandService is the callback surface workflow-service workers use to
// execute loan business steps (mirror of crm CustomerCommandService).
type LoanCommandServiceClient interface {
	UpdateContractStatus(ctx context.Context, in *UpdateContractStatusRequest, opts ...grpc.CallOption) (*UpdateContractStatusResponse, error)
	CheckAdjustment(ctx context.Context, in *CheckAdjustmentRequest, opts ...grpc.CallOption) (*CheckAdjustmentResponse, error)
	ResolveAdjustment(ctx context.Context, in *ResolveAdjustmentRequest, opts ...grpc.CallOption) (*ResolveAdjustmentResponse, error)
	CheckDisbursement(ctx context.Context, in *CheckDisbursementRequest, opts ...grpc.CallOption) (*CheckDisbursementResponse, error)
	GetDisbursementPostingDetail(ctx context.Context, in *GetDisbursementPostingDetailRequest, opts ...grpc.CallOption) (*DisbursementPostingDetail, error)
	SettleDisbursement(ctx context.Context, in *SettleDisbursementRequest, opts ...grpc.CallOption) (*SettleDisbursementResponse, error)
	ResolveDisbursement(ctx context.Context, in *ResolveDisbursementRequest, opts ...grpc.CallOption) (*ResolveDisbursementResponse, error)
}

type loanCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanCommandServiceClient(cc grpc.ClientConnInterface) LoanCommandServiceClient {
	return &loanCommandServiceClient{cc}
}

func (c *loanCommandServiceClient) UpdateContractStatus(ctx context.Context, in *UpdateContractStatusRequest, opts ...grpc.CallOption) (*UpdateContractStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContractStatusResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_UpdateContractStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckAdjustment(ctx context.Context, in *CheckAdjustmentRequest, opts ...grpc.CallOption) (*CheckAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAdjustmentResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveAdjustment(ctx context.Context, in *ResolveAdjustmentRequest, opts ...grpc.CallOption) (*ResolveAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAdjustmentResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckDisbursement(ctx context.Context, in *CheckDisbursementRequest, opts ...grpc.CallOption) (*CheckDisbursementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckDisbursementResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckDisbursement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) GetDisbursementPostingDetail(ctx context.Context, in *GetDisbursementPostingDetailRequest, opts ...grpc.CallOption) (*DisbursementPostingDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisbursementPostingDetail)
	err := c.cc.Invoke(ctx, LoanCommandService_GetDisbursementPostingDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) SettleDisbursement(ctx context.Context, in *SettleDisbursementRequest, opts ...grpc.CallOption) (*SettleDisbursementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleDisbursementResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_SettleDisbursement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveDisbursement(ctx context.Context, in *ResolveDisbursementRequest, opts ...grpc.CallOption) (*ResolveDisbursementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveDisbursementResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveDisbursement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanCommandServiceServer is the server API for LoanCommandService service.
// All implementations must embed UnimplementedLoanCommandServiceServer
// for forward compatibility.
//
// LoanCommandService is the callback surface workflow-service workers use to
// execute loan business steps (mirror of crm CustomerCommandService).
type LoanCommandServiceServer interface {
	UpdateContractStatus(context.Context, *UpdateContractStatusRequest) (*UpdateContractStatusResponse, error)
	CheckAdjustment(context.Context, *CheckAdjustmentRequest) (*CheckAdjustmentResponse, error)
	ResolveAdjustment(context.Context, *ResolveAdjustmentRequest) (*ResolveAdjustmentResponse, error)
	CheckDisbursement(context.Context, *CheckDisbursementRequest) (*CheckDisbursementResponse, error)
	GetDisbursementPostingDetail(context.Context, *GetDisbursementPostingDetailRequest) (*DisbursementPostingDetail, error)
	SettleDisbursement(context.Context, *SettleDisbursementRequest) (*SettleDisbursementResponse, error)
	ResolveDisbursement(context.Context, *ResolveDisbursementRequest) (*ResolveDisbursementResponse, error)
	mustEmbedUnimplementedLoanCommandServiceServer()
}

// UnimplementedLoanCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanCommandServiceServer struct{}

func (UnimplementedLoanCommandServiceServer) UpdateContractStatus(context.Context, *UpdateContractStatusRequest) (*UpdateContractStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContractStatus not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckAdjustment(context.Context, *CheckAdjustmentRequest) (*CheckAdjustmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAdjustment not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveAdjustment(context.Context, *ResolveAdjustmentRequest) (*ResolveAdjustmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAdjustment not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckDisbursement(context.Context, *CheckDisbursementRequest) (*CheckDisbursementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDisbursement not implemented")
}
func (UnimplementedLoanCommandServiceServer) GetDisbursementPostingDetail(context.Context, *GetDisbursementPostingDetailRequest) (*DisbursementPostingDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDisbursementPostingDetail not implemented")
}
func (UnimplementedLoanCommandServiceServer) SettleDisbursement(context.Context, *SettleDisbursementRequest) (*SettleDisbursementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleDisbursement not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveDisbursement(context.Context, *ResolveDisbursementRequest) (*ResolveDisbursementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDisbursement not implemented")
}
func (UnimplementedLoanCommandServiceServer) mustEmbedUnimplementedLoanCommandServiceServer() {}
func (UnimplementedLoanCommandServiceServer) testEmbeddedByValue()                            {}

// UnsafeLoanCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanCommandServiceServer will
// result in compilation errors.
type UnsafeLoanCommandServiceServer interface {
	mustEmbedUnimplementedLoanCommandServiceServer()
}

func RegisterLoanCommandServiceServer(s grpc.ServiceRegistrar, srv LoanCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedLoanCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanCommandService_ServiceDesc, srv)
}

func _LoanCommandService_UpdateContractStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContractStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).UpdateContractStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_UpdateContractStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).UpdateContractStatus(ctx, req.(*UpdateContractStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckAdjustment(ctx, req.(*CheckAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveAdjustment(ctx, req.(*ResolveAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDisbursementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckDisbursement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckDisbursement(ctx, req.(*CheckDisbursementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_GetDisbursementPostingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDisbursementPostingDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).GetDisbursementPostingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_GetDisbursementPostingDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).GetDisbursementPostingDetail(ctx, req.(*GetDisbursementPostingDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_SettleDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleDisbursementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).SettleDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_SettleDisbursement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).SettleDisbursement(ctx, req.(*SettleDisbursementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDisbursementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveDisbursement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveDisbursement(ctx, req.(*ResolveDisbursementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanCommandService_ServiceDesc is the grpc.ServiceDesc for LoanCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arda.loan.v1.LoanCommandService",
	HandlerType: (*LoanCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateContractStatus",
			Handler:    _LoanCommandService_UpdateContractStatus_Handler,
		},
		{
			MethodName: "CheckAdjustment",
			Handler:    _LoanCommandService_CheckAdjustment_Handler,
		},
		{
			MethodName: "ResolveAdjustment",
			Handler:    _LoanCommandService_ResolveAdjustment_Handler,
		},
		{
			MethodName: "CheckDisbursement",
			Handler:    _LoanCommandService_CheckDisbursement_Handler,
		},
		{
			MethodName: "GetDisbursementPostingDetail",
			Handler:    _LoanCommandService_GetDisbursementPostingDetail_Handler,
		},
		{
			MethodName: "SettleDisbursement",
			Handler:    _LoanCommandService_SettleDisbursement_Handler,
		},
		{
			MethodName: "ResolveDisbursement",
			Handler:    _LoanCommandService_ResolveDisbursement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arda/loan/v1/loan.proto",
}
