// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: arda/loan/v1/loan.proto

package loanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanCommandService_UpdateContractStatus_FullMethodName         = "/arda.loan.v1.LoanCommandService/UpdateContractStatus"
	LoanCommandService_GetContract_FullMethodName                  = "/arda.loan.v1.LoanCommandService/GetContract"
	LoanCommandService_CheckFormation_FullMethodName               = "/arda.loan.v1.LoanCommandService/CheckFormation"
	LoanCommandService_CheckAdjustment_FullMethodName              = "/arda.loan.v1.LoanCommandService/CheckAdjustment"
	LoanCommandService_ResolveAdjustment_FullMethodName            = "/arda.loan.v1.LoanCommandService/ResolveAdjustment"
	LoanCommandService_CheckDisbursement_FullMethodName            = "/arda.loan.v1.LoanCommandService/CheckDisbursement"
	LoanCommandService_GetDisbursementPostingDetail_FullMethodName = "/arda.loan.v1.LoanCommandService/GetDisbursementPostingDetail"
	LoanCommandService_SettleDisbursement_FullMethodName           = "/arda.loan.v1.LoanCommandService/SettleDisbursement"
	LoanCommandService_ResolveDisbursement_FullMethodName          = "/arda.loan.v1.LoanCommandService/ResolveDisbursement"
	LoanCommandService_CheckCollection_FullMethodName              = "/arda.loan.v1.LoanCommandService/CheckCollection"
	LoanCommandService_GetCollectionPostingDetail_FullMethodName   = "/arda.loan.v1.LoanCommandService/GetCollectionPostingDetail"
	LoanCommandService_SettleCollection_FullMethodName             = "/arda.loan.v1.LoanCommandService/SettleCollection"
	LoanCommandService_ResolveCollection_FullMethodName            = "/arda.loan.v1.LoanCommandService/ResolveCollection"
	LoanCommandService_GetBatchPostingDetail_FullMethodName        = "/arda.loan.v1.LoanCommandService/GetBatchPostingDetail"
	LoanCommandService_CheckBatch_FullMethodName                   = "/arda.loan.v1.LoanCommandService/CheckBatch"
	LoanCommandService_SettleBatch_FullMethodName                  = "/arda.loan.v1.LoanCommandService/SettleBatch"
	LoanCommandService_ResolveBatch_FullMethodName                 = "/arda.loan.v1.LoanCommandService/ResolveBatch"
	LoanCommandService_CheckGeneralProvision_FullMethodName        = "/arda.loan.v1.LoanCommandService/CheckGeneralProvision"
	LoanCommandService_ResolveGeneralProvision_FullMethodName      = "/arda.loan.v1.LoanCommandService/ResolveGeneralProvision"
	LoanCommandService_CheckSpecificProvision_FullMethodName       = "/arda.loan.v1.LoanCommandService/CheckSpecificProvision"
	LoanCommandService_ResolveSpecificProvision_FullMethodName     = "/arda.loan.v1.LoanCommandService/ResolveSpecificProvision"
)

// LoanCommandServiceClient is the client API for LoanCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LoanCommandService is the callback surface workflow-service workers use to
// execute loan business steps (mirror of crm CustomerCommandService).
type LoanCommandServiceClient interface {
	UpdateContractStatus(ctx context.Context, in *UpdateContractStatusRequest, opts ...grpc.CallOption) (*UpdateContractStatusResponse, error)
	GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*ContractBrief, error)
	CheckFormation(ctx context.Context, in *CheckFormationRequest, opts ...grpc.CallOption) (*CheckFormationResponse, error)
	CheckAdjustment(ctx context.Context, in *CheckAdjustmentRequest, opts ...grpc.CallOption) (*CheckAdjustmentResponse, error)
	ResolveAdjustment(ctx context.Context, in *ResolveAdjustmentRequest, opts ...grpc.CallOption) (*ResolveAdjustmentResponse, error)
	CheckDisbursement(ctx context.Context, in *CheckDisbursementRequest, opts ...grpc.CallOption) (*CheckDisbursementResponse, error)
	GetDisbursementPostingDetail(ctx context.Context, in *GetDisbursementPostingDetailRequest, opts ...grpc.CallOption) (*DisbursementPostingDetail, error)
	SettleDisbursement(ctx context.Context, in *SettleDisbursementRequest, opts ...grpc.CallOption) (*SettleDisbursementResponse, error)
	ResolveDisbursement(ctx context.Context, in *ResolveDisbursementRequest, opts ...grpc.CallOption) (*ResolveDisbursementResponse, error)
	CheckCollection(ctx context.Context, in *CheckCollectionRequest, opts ...grpc.CallOption) (*CheckCollectionResponse, error)
	GetCollectionPostingDetail(ctx context.Context, in *GetCollectionPostingDetailRequest, opts ...grpc.CallOption) (*CollectionPostingDetail, error)
	SettleCollection(ctx context.Context, in *SettleCollectionRequest, opts ...grpc.CallOption) (*SettleCollectionResponse, error)
	ResolveCollection(ctx context.Context, in *ResolveCollectionRequest, opts ...grpc.CallOption) (*ResolveCollectionResponse, error)
	GetBatchPostingDetail(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*BatchPostingDetail, error)
	CheckBatch(ctx context.Context, in *CheckBatchRequest, opts ...grpc.CallOption) (*CheckBatchResponse, error)
	SettleBatch(ctx context.Context, in *SettleBatchRequest, opts ...grpc.CallOption) (*SettleBatchResponse, error)
	ResolveBatch(ctx context.Context, in *ResolveBatchRequest, opts ...grpc.CallOption) (*ResolveBatchResponse, error)
	CheckGeneralProvision(ctx context.Context, in *CheckGeneralProvisionRequest, opts ...grpc.CallOption) (*CheckGeneralProvisionResponse, error)
	ResolveGeneralProvision(ctx context.Context, in *ResolveGeneralProvisionRequest, opts ...grpc.CallOption) (*ResolveGeneralProvisionResponse, error)
	CheckSpecificProvision(ctx context.Context, in *CheckSpecificProvisionRequest, opts ...grpc.CallOption) (*CheckSpecificProvisionResponse, error)
	ResolveSpecificProvision(ctx context.Context, in *ResolveSpecificProvisionRequest, opts ...grpc.CallOption) (*ResolveSpecificProvisionResponse, error)
}

type loanCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanCommandServiceClient(cc grpc.ClientConnInterface) LoanCommandServiceClient {
	return &loanCommandServiceClient{cc}
}

func (c *loanCommandServiceClient) UpdateContractStatus(ctx context.Context, in *UpdateContractStatusRequest, opts ...grpc.CallOption) (*UpdateContractStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContractStatusResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_UpdateContractStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*ContractBrief, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractBrief)
	err := c.cc.Invoke(ctx, LoanCommandService_GetContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckFormation(ctx context.Context, in *CheckFormationRequest, opts ...grpc.CallOption) (*CheckFormationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFormationResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckFormation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckAdjustment(ctx context.Context, in *CheckAdjustmentRequest, opts ...grpc.CallOption) (*CheckAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAdjustmentResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveAdjustment(ctx context.Context, in *ResolveAdjustmentRequest, opts ...grpc.CallOption) (*ResolveAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAdjustmentResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckDisbursement(ctx context.Context, in *CheckDisbursementRequest, opts ...grpc.CallOption) (*CheckDisbursementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckDisbursementResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckDisbursement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) GetDisbursementPostingDetail(ctx context.Context, in *GetDisbursementPostingDetailRequest, opts ...grpc.CallOption) (*DisbursementPostingDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisbursementPostingDetail)
	err := c.cc.Invoke(ctx, LoanCommandService_GetDisbursementPostingDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) SettleDisbursement(ctx context.Context, in *SettleDisbursementRequest, opts ...grpc.CallOption) (*SettleDisbursementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleDisbursementResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_SettleDisbursement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveDisbursement(ctx context.Context, in *ResolveDisbursementRequest, opts ...grpc.CallOption) (*ResolveDisbursementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveDisbursementResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveDisbursement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckCollection(ctx context.Context, in *CheckCollectionRequest, opts ...grpc.CallOption) (*CheckCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCollectionResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) GetCollectionPostingDetail(ctx context.Context, in *GetCollectionPostingDetailRequest, opts ...grpc.CallOption) (*CollectionPostingDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionPostingDetail)
	err := c.cc.Invoke(ctx, LoanCommandService_GetCollectionPostingDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) SettleCollection(ctx context.Context, in *SettleCollectionRequest, opts ...grpc.CallOption) (*SettleCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleCollectionResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_SettleCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveCollection(ctx context.Context, in *ResolveCollectionRequest, opts ...grpc.CallOption) (*ResolveCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveCollectionResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) GetBatchPostingDetail(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*BatchPostingDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPostingDetail)
	err := c.cc.Invoke(ctx, LoanCommandService_GetBatchPostingDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckBatch(ctx context.Context, in *CheckBatchRequest, opts ...grpc.CallOption) (*CheckBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBatchResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) SettleBatch(ctx context.Context, in *SettleBatchRequest, opts ...grpc.CallOption) (*SettleBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleBatchResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_SettleBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveBatch(ctx context.Context, in *ResolveBatchRequest, opts ...grpc.CallOption) (*ResolveBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveBatchResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckGeneralProvision(ctx context.Context, in *CheckGeneralProvisionRequest, opts ...grpc.CallOption) (*CheckGeneralProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckGeneralProvisionResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckGeneralProvision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveGeneralProvision(ctx context.Context, in *ResolveGeneralProvisionRequest, opts ...grpc.CallOption) (*ResolveGeneralProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveGeneralProvisionResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveGeneralProvision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) CheckSpecificProvision(ctx context.Context, in *CheckSpecificProvisionRequest, opts ...grpc.CallOption) (*CheckSpecificProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSpecificProvisionResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_CheckSpecificProvision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanCommandServiceClient) ResolveSpecificProvision(ctx context.Context, in *ResolveSpecificProvisionRequest, opts ...grpc.CallOption) (*ResolveSpecificProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSpecificProvisionResponse)
	err := c.cc.Invoke(ctx, LoanCommandService_ResolveSpecificProvision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanCommandServiceServer is the server API for LoanCommandService service.
// All implementations must embed UnimplementedLoanCommandServiceServer
// for forward compatibility.
//
// LoanCommandService is the callback surface workflow-service workers use to
// execute loan business steps (mirror of crm CustomerCommandService).
type LoanCommandServiceServer interface {
	UpdateContractStatus(context.Context, *UpdateContractStatusRequest) (*UpdateContractStatusResponse, error)
	GetContract(context.Context, *GetContractRequest) (*ContractBrief, error)
	CheckFormation(context.Context, *CheckFormationRequest) (*CheckFormationResponse, error)
	CheckAdjustment(context.Context, *CheckAdjustmentRequest) (*CheckAdjustmentResponse, error)
	ResolveAdjustment(context.Context, *ResolveAdjustmentRequest) (*ResolveAdjustmentResponse, error)
	CheckDisbursement(context.Context, *CheckDisbursementRequest) (*CheckDisbursementResponse, error)
	GetDisbursementPostingDetail(context.Context, *GetDisbursementPostingDetailRequest) (*DisbursementPostingDetail, error)
	SettleDisbursement(context.Context, *SettleDisbursementRequest) (*SettleDisbursementResponse, error)
	ResolveDisbursement(context.Context, *ResolveDisbursementRequest) (*ResolveDisbursementResponse, error)
	CheckCollection(context.Context, *CheckCollectionRequest) (*CheckCollectionResponse, error)
	GetCollectionPostingDetail(context.Context, *GetCollectionPostingDetailRequest) (*CollectionPostingDetail, error)
	SettleCollection(context.Context, *SettleCollectionRequest) (*SettleCollectionResponse, error)
	ResolveCollection(context.Context, *ResolveCollectionRequest) (*ResolveCollectionResponse, error)
	GetBatchPostingDetail(context.Context, *GetBatchRequest) (*BatchPostingDetail, error)
	CheckBatch(context.Context, *CheckBatchRequest) (*CheckBatchResponse, error)
	SettleBatch(context.Context, *SettleBatchRequest) (*SettleBatchResponse, error)
	ResolveBatch(context.Context, *ResolveBatchRequest) (*ResolveBatchResponse, error)
	CheckGeneralProvision(context.Context, *CheckGeneralProvisionRequest) (*CheckGeneralProvisionResponse, error)
	ResolveGeneralProvision(context.Context, *ResolveGeneralProvisionRequest) (*ResolveGeneralProvisionResponse, error)
	CheckSpecificProvision(context.Context, *CheckSpecificProvisionRequest) (*CheckSpecificProvisionResponse, error)
	ResolveSpecificProvision(context.Context, *ResolveSpecificProvisionRequest) (*ResolveSpecificProvisionResponse, error)
	mustEmbedUnimplementedLoanCommandServiceServer()
}

// UnimplementedLoanCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanCommandServiceServer struct{}

func (UnimplementedLoanCommandServiceServer) UpdateContractStatus(context.Context, *UpdateContractStatusRequest) (*UpdateContractStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContractStatus not implemented")
}
func (UnimplementedLoanCommandServiceServer) GetContract(context.Context, *GetContractRequest) (*ContractBrief, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckFormation(context.Context, *CheckFormationRequest) (*CheckFormationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckFormation not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckAdjustment(context.Context, *CheckAdjustmentRequest) (*CheckAdjustmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAdjustment not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveAdjustment(context.Context, *ResolveAdjustmentRequest) (*ResolveAdjustmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAdjustment not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckDisbursement(context.Context, *CheckDisbursementRequest) (*CheckDisbursementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDisbursement not implemented")
}
func (UnimplementedLoanCommandServiceServer) GetDisbursementPostingDetail(context.Context, *GetDisbursementPostingDetailRequest) (*DisbursementPostingDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDisbursementPostingDetail not implemented")
}
func (UnimplementedLoanCommandServiceServer) SettleDisbursement(context.Context, *SettleDisbursementRequest) (*SettleDisbursementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleDisbursement not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveDisbursement(context.Context, *ResolveDisbursementRequest) (*ResolveDisbursementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDisbursement not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckCollection(context.Context, *CheckCollectionRequest) (*CheckCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCollection not implemented")
}
func (UnimplementedLoanCommandServiceServer) GetCollectionPostingDetail(context.Context, *GetCollectionPostingDetailRequest) (*CollectionPostingDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionPostingDetail not implemented")
}
func (UnimplementedLoanCommandServiceServer) SettleCollection(context.Context, *SettleCollectionRequest) (*SettleCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleCollection not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveCollection(context.Context, *ResolveCollectionRequest) (*ResolveCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveCollection not implemented")
}
func (UnimplementedLoanCommandServiceServer) GetBatchPostingDetail(context.Context, *GetBatchRequest) (*BatchPostingDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchPostingDetail not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckBatch(context.Context, *CheckBatchRequest) (*CheckBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBatch not implemented")
}
func (UnimplementedLoanCommandServiceServer) SettleBatch(context.Context, *SettleBatchRequest) (*SettleBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleBatch not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveBatch(context.Context, *ResolveBatchRequest) (*ResolveBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveBatch not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckGeneralProvision(context.Context, *CheckGeneralProvisionRequest) (*CheckGeneralProvisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckGeneralProvision not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveGeneralProvision(context.Context, *ResolveGeneralProvisionRequest) (*ResolveGeneralProvisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveGeneralProvision not implemented")
}
func (UnimplementedLoanCommandServiceServer) CheckSpecificProvision(context.Context, *CheckSpecificProvisionRequest) (*CheckSpecificProvisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSpecificProvision not implemented")
}
func (UnimplementedLoanCommandServiceServer) ResolveSpecificProvision(context.Context, *ResolveSpecificProvisionRequest) (*ResolveSpecificProvisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSpecificProvision not implemented")
}
func (UnimplementedLoanCommandServiceServer) mustEmbedUnimplementedLoanCommandServiceServer() {}
func (UnimplementedLoanCommandServiceServer) testEmbeddedByValue()                            {}

// UnsafeLoanCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanCommandServiceServer will
// result in compilation errors.
type UnsafeLoanCommandServiceServer interface {
	mustEmbedUnimplementedLoanCommandServiceServer()
}

func RegisterLoanCommandServiceServer(s grpc.ServiceRegistrar, srv LoanCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedLoanCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanCommandService_ServiceDesc, srv)
}

func _LoanCommandService_UpdateContractStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContractStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).UpdateContractStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_UpdateContractStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).UpdateContractStatus(ctx, req.(*UpdateContractStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_GetContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).GetContract(ctx, req.(*GetContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckFormation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFormationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckFormation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckFormation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckFormation(ctx, req.(*CheckFormationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckAdjustment(ctx, req.(*CheckAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveAdjustment(ctx, req.(*ResolveAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDisbursementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckDisbursement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckDisbursement(ctx, req.(*CheckDisbursementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_GetDisbursementPostingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDisbursementPostingDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).GetDisbursementPostingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_GetDisbursementPostingDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).GetDisbursementPostingDetail(ctx, req.(*GetDisbursementPostingDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_SettleDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleDisbursementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).SettleDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_SettleDisbursement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).SettleDisbursement(ctx, req.(*SettleDisbursementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDisbursementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveDisbursement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveDisbursement(ctx, req.(*ResolveDisbursementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckCollection(ctx, req.(*CheckCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_GetCollectionPostingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionPostingDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).GetCollectionPostingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_GetCollectionPostingDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).GetCollectionPostingDetail(ctx, req.(*GetCollectionPostingDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_SettleCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).SettleCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_SettleCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).SettleCollection(ctx, req.(*SettleCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveCollection(ctx, req.(*ResolveCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_GetBatchPostingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).GetBatchPostingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_GetBatchPostingDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).GetBatchPostingDetail(ctx, req.(*GetBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckBatch(ctx, req.(*CheckBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_SettleBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).SettleBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_SettleBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).SettleBatch(ctx, req.(*SettleBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveBatch(ctx, req.(*ResolveBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckGeneralProvision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckGeneralProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckGeneralProvision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckGeneralProvision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckGeneralProvision(ctx, req.(*CheckGeneralProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveGeneralProvision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveGeneralProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveGeneralProvision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveGeneralProvision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveGeneralProvision(ctx, req.(*ResolveGeneralProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_CheckSpecificProvision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSpecificProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).CheckSpecificProvision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_CheckSpecificProvision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).CheckSpecificProvision(ctx, req.(*CheckSpecificProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanCommandService_ResolveSpecificProvision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSpecificProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCommandServiceServer).ResolveSpecificProvision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCommandService_ResolveSpecificProvision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCommandServiceServer).ResolveSpecificProvision(ctx, req.(*ResolveSpecificProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanCommandService_ServiceDesc is the grpc.ServiceDesc for LoanCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arda.loan.v1.LoanCommandService",
	HandlerType: (*LoanCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateContractStatus",
			Handler:    _LoanCommandService_UpdateContractStatus_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _LoanCommandService_GetContract_Handler,
		},
		{
			MethodName: "CheckFormation",
			Handler:    _LoanCommandService_CheckFormation_Handler,
		},
		{
			MethodName: "CheckAdjustment",
			Handler:    _LoanCommandService_CheckAdjustment_Handler,
		},
		{
			MethodName: "ResolveAdjustment",
			Handler:    _LoanCommandService_ResolveAdjustment_Handler,
		},
		{
			MethodName: "CheckDisbursement",
			Handler:    _LoanCommandService_CheckDisbursement_Handler,
		},
		{
			MethodName: "GetDisbursementPostingDetail",
			Handler:    _LoanCommandService_GetDisbursementPostingDetail_Handler,
		},
		{
			MethodName: "SettleDisbursement",
			Handler:    _LoanCommandService_SettleDisbursement_Handler,
		},
		{
			MethodName: "ResolveDisbursement",
			Handler:    _LoanCommandService_ResolveDisbursement_Handler,
		},
		{
			MethodName: "CheckCollection",
			Handler:    _LoanCommandService_CheckCollection_Handler,
		},
		{
			MethodName: "GetCollectionPostingDetail",
			Handler:    _LoanCommandService_GetCollectionPostingDetail_Handler,
		},
		{
			MethodName: "SettleCollection",
			Handler:    _LoanCommandService_SettleCollection_Handler,
		},
		{
			MethodName: "ResolveCollection",
			Handler:    _LoanCommandService_ResolveCollection_Handler,
		},
		{
			MethodName: "GetBatchPostingDetail",
			Handler:    _LoanCommandService_GetBatchPostingDetail_Handler,
		},
		{
			MethodName: "CheckBatch",
			Handler:    _LoanCommandService_CheckBatch_Handler,
		},
		{
			MethodName: "SettleBatch",
			Handler:    _LoanCommandService_SettleBatch_Handler,
		},
		{
			MethodName: "ResolveBatch",
			Handler:    _LoanCommandService_ResolveBatch_Handler,
		},
		{
			MethodName: "CheckGeneralProvision",
			Handler:    _LoanCommandService_CheckGeneralProvision_Handler,
		},
		{
			MethodName: "ResolveGeneralProvision",
			Handler:    _LoanCommandService_ResolveGeneralProvision_Handler,
		},
		{
			MethodName: "CheckSpecificProvision",
			Handler:    _LoanCommandService_CheckSpecificProvision_Handler,
		},
		{
			MethodName: "ResolveSpecificProvision",
			Handler:    _LoanCommandService_ResolveSpecificProvision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arda/loan/v1/loan.proto",
}
