// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: arda/loan/v1/loan.proto

package loanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateContractStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContractStatusRequest) Reset() {
	*x = UpdateContractStatusRequest{}
	mi := &file_arda_loan_v1_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContractStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractStatusRequest) ProtoMessage() {}

func (x *UpdateContractStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_loan_v1_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateContractStatusRequest) Descriptor() ([]byte, []int) {
	return file_arda_loan_v1_loan_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateContractStatusRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *UpdateContractStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateContractStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContractStatusResponse) Reset() {
	*x = UpdateContractStatusResponse{}
	mi := &file_arda_loan_v1_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContractStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractStatusResponse) ProtoMessage() {}

func (x *UpdateContractStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_loan_v1_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateContractStatusResponse) Descriptor() ([]byte, []int) {
	return file_arda_loan_v1_loan_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateContractStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CheckAdjustmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	AdjustmentId  string                 `protobuf:"bytes,2,opt,name=adjustment_id,json=adjustmentId,proto3" json:"adjustment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAdjustmentRequest) Reset() {
	*x = CheckAdjustmentRequest{}
	mi := &file_arda_loan_v1_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAdjustmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAdjustmentRequest) ProtoMessage() {}

func (x *CheckAdjustmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_loan_v1_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAdjustmentRequest.ProtoReflect.Descriptor instead.
func (*CheckAdjustmentRequest) Descriptor() ([]byte, []int) {
	return file_arda_loan_v1_loan_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAdjustmentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CheckAdjustmentRequest) GetAdjustmentId() string {
	if x != nil {
		return x.AdjustmentId
	}
	return ""
}

type CheckAdjustmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAdjustmentResponse) Reset() {
	*x = CheckAdjustmentResponse{}
	mi := &file_arda_loan_v1_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAdjustmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAdjustmentResponse) ProtoMessage() {}

func (x *CheckAdjustmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_loan_v1_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAdjustmentResponse.ProtoReflect.Descriptor instead.
func (*CheckAdjustmentResponse) Descriptor() ([]byte, []int) {
	return file_arda_loan_v1_loan_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAdjustmentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckAdjustmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveAdjustmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	AdjustmentId  string                 `protobuf:"bytes,2,opt,name=adjustment_id,json=adjustmentId,proto3" json:"adjustment_id,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"` // APPROVE | REJECT | CANCEL
	DecidedBy     string                 `protobuf:"bytes,4,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAdjustmentRequest) Reset() {
	*x = ResolveAdjustmentRequest{}
	mi := &file_arda_loan_v1_loan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAdjustmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAdjustmentRequest) ProtoMessage() {}

func (x *ResolveAdjustmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_loan_v1_loan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAdjustmentRequest.ProtoReflect.Descriptor instead.
func (*ResolveAdjustmentRequest) Descriptor() ([]byte, []int) {
	return file_arda_loan_v1_loan_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveAdjustmentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResolveAdjustmentRequest) GetAdjustmentId() string {
	if x != nil {
		return x.AdjustmentId
	}
	return ""
}

func (x *ResolveAdjustmentRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ResolveAdjustmentRequest) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

func (x *ResolveAdjustmentRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ResolveAdjustmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAdjustmentResponse) Reset() {
	*x = ResolveAdjustmentResponse{}
	mi := &file_arda_loan_v1_loan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAdjustmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAdjustmentResponse) ProtoMessage() {}

func (x *ResolveAdjustmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_loan_v1_loan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAdjustmentResponse.ProtoReflect.Descriptor instead.
func (*ResolveAdjustmentResponse) Descriptor() ([]byte, []int) {
	return file_arda_loan_v1_loan_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveAdjustmentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_arda_loan_v1_loan_proto protoreflect.FileDescriptor

const file_arda_loan_v1_loan_proto_rawDesc = "" +
	"\n" +
	"\x17arda/loan/v1/loan.proto\x12\farda.loan.v1\"V\n" +
	"\x1bUpdateContractStatusRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\".\n" +
	"\x1cUpdateContractStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Q\n" +
	"\x16CheckAdjustmentRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12#\n" +
	"\radjustment_id\x18\x02 \x01(\tR\fadjustmentId\"C\n" +
	"\x17CheckAdjustmentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa2\x01\n" +
	"\x18ResolveAdjustmentRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12#\n" +
	"\radjustment_id\x18\x02 \x01(\tR\fadjustmentId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x1d\n" +
	"\n" +
	"decided_by\x18\x04 \x01(\tR\tdecidedBy\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"+\n" +
	"\x19ResolveAdjustmentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xc9\x02\n" +
	"\x12LoanCommandService\x12m\n" +
	"\x14UpdateContractStatus\x12).arda.loan.v1.UpdateContractStatusRequest\x1a*.arda.loan.v1.UpdateContractStatusResponse\x12^\n" +
	"\x0fCheckAdjustment\x12$.arda.loan.v1.CheckAdjustmentRequest\x1a%.arda.loan.v1.CheckAdjustmentResponse\x12d\n" +
	"\x11ResolveAdjustment\x12&.arda.loan.v1.ResolveAdjustmentRequest\x1a'.arda.loan.v1.ResolveAdjustmentResponseB=Z;github.com/arda-labs/arda/libs/go/arda-proto/loan/v1;loanv1b\x06proto3"

var (
	file_arda_loan_v1_loan_proto_rawDescOnce sync.Once
	file_arda_loan_v1_loan_proto_rawDescData []byte
)

func file_arda_loan_v1_loan_proto_rawDescGZIP() []byte {
	file_arda_loan_v1_loan_proto_rawDescOnce.Do(func() {
		file_arda_loan_v1_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arda_loan_v1_loan_proto_rawDesc), len(file_arda_loan_v1_loan_proto_rawDesc)))
	})
	return file_arda_loan_v1_loan_proto_rawDescData
}

var file_arda_loan_v1_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_arda_loan_v1_loan_proto_goTypes = []any{
	(*UpdateContractStatusRequest)(nil),  // 0: arda.loan.v1.UpdateContractStatusRequest
	(*UpdateContractStatusResponse)(nil), // 1: arda.loan.v1.UpdateContractStatusResponse
	(*CheckAdjustmentRequest)(nil),       // 2: arda.loan.v1.CheckAdjustmentRequest
	(*CheckAdjustmentResponse)(nil),      // 3: arda.loan.v1.CheckAdjustmentResponse
	(*ResolveAdjustmentRequest)(nil),     // 4: arda.loan.v1.ResolveAdjustmentRequest
	(*ResolveAdjustmentResponse)(nil),    // 5: arda.loan.v1.ResolveAdjustmentResponse
}
var file_arda_loan_v1_loan_proto_depIdxs = []int32{
	0, // 0: arda.loan.v1.LoanCommandService.UpdateContractStatus:input_type -> arda.loan.v1.UpdateContractStatusRequest
	2, // 1: arda.loan.v1.LoanCommandService.CheckAdjustment:input_type -> arda.loan.v1.CheckAdjustmentRequest
	4, // 2: arda.loan.v1.LoanCommandService.ResolveAdjustment:input_type -> arda.loan.v1.ResolveAdjustmentRequest
	1, // 3: arda.loan.v1.LoanCommandService.UpdateContractStatus:output_type -> arda.loan.v1.UpdateContractStatusResponse
	3, // 4: arda.loan.v1.LoanCommandService.CheckAdjustment:output_type -> arda.loan.v1.CheckAdjustmentResponse
	5, // 5: arda.loan.v1.LoanCommandService.ResolveAdjustment:output_type -> arda.loan.v1.ResolveAdjustmentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arda_loan_v1_loan_proto_init() }
func file_arda_loan_v1_loan_proto_init() {
	if File_arda_loan_v1_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arda_loan_v1_loan_proto_rawDesc), len(file_arda_loan_v1_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arda_loan_v1_loan_proto_goTypes,
		DependencyIndexes: file_arda_loan_v1_loan_proto_depIdxs,
		MessageInfos:      file_arda_loan_v1_loan_proto_msgTypes,
	}.Build()
	File_arda_loan_v1_loan_proto = out.File
	file_arda_loan_v1_loan_proto_goTypes = nil
	file_arda_loan_v1_loan_proto_depIdxs = nil
}
