version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/capital-service ./cmd/capital-service

  run:
    cmds:
      - go run ./cmd/capital-service

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - go vet ./...

  docker:
    cmds:
      - docker build -t capital-service:latest .
