-- +goose Up
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS department VARCHAR(255) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS position VARCHAR(255) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS employee_id VARCHAR(64) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS approval_level VARCHAR(64) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS daily_limit VARCHAR(128) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '';

-- +goose Down
ALTER TABLE iam_users DROP COLUMN IF EXISTS department;
ALTER TABLE iam_users DROP COLUMN IF EXISTS position;
ALTER TABLE iam_users DROP COLUMN IF EXISTS employee_id;
ALTER TABLE iam_users DROP COLUMN IF EXISTS approval_level;
ALTER TABLE iam_users DROP COLUMN IF EXISTS daily_limit;
ALTER TABLE iam_users DROP COLUMN IF EXISTS bio;
