-- +goose Up
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS first_name VARCHAR(128) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS last_name VARCHAR(128) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(32) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS birthdate VARCHAR(64) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS gender VARCHAR(16) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS address VARCHAR(512) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS country VARCHAR(128) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS cover_file_id VARCHAR(64) DEFAULT '';
ALTER TABLE iam_users ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR(512) DEFAULT '';

-- +goose Down
ALTER TABLE iam_users DROP COLUMN IF EXISTS first_name;
ALTER TABLE iam_users DROP COLUMN IF EXISTS last_name;
ALTER TABLE iam_users DROP COLUMN IF EXISTS phone_number;
ALTER TABLE iam_users DROP COLUMN IF EXISTS birthdate;
ALTER TABLE iam_users DROP COLUMN IF EXISTS gender;
ALTER TABLE iam_users DROP COLUMN IF EXISTS address;
ALTER TABLE iam_users DROP COLUMN IF EXISTS country;
ALTER TABLE iam_users DROP COLUMN IF EXISTS cover_file_id;
ALTER TABLE iam_users DROP COLUMN IF EXISTS cover_image_url;
