// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: arda/capital/v1/capital.proto

package capitalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// kind = CONTRACT_FORMATION | CONTRACT_AMENDMENT | MOVEMENT.
type CheckRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	RefId         string                 `protobuf:"bytes,2,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequestRequest) Reset() {
	*x = CheckRequestRequest{}
	mi := &file_arda_capital_v1_capital_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequestRequest) ProtoMessage() {}

func (x *CheckRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_capital_v1_capital_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequestRequest.ProtoReflect.Descriptor instead.
func (*CheckRequestRequest) Descriptor() ([]byte, []int) {
	return file_arda_capital_v1_capital_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequestRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CheckRequestRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type CheckRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequestResponse) Reset() {
	*x = CheckRequestResponse{}
	mi := &file_arda_capital_v1_capital_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequestResponse) ProtoMessage() {}

func (x *CheckRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_capital_v1_capital_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequestResponse.ProtoReflect.Descriptor instead.
func (*CheckRequestResponse) Descriptor() ([]byte, []int) {
	return file_arda_capital_v1_capital_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRequestResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// decision = APPROVE | REJECT.
type ResolveRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	RefId         string                 `protobuf:"bytes,2,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequestRequest) Reset() {
	*x = ResolveRequestRequest{}
	mi := &file_arda_capital_v1_capital_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequestRequest) ProtoMessage() {}

func (x *ResolveRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_capital_v1_capital_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequestRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequestRequest) Descriptor() ([]byte, []int) {
	return file_arda_capital_v1_capital_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequestRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResolveRequestRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *ResolveRequestRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ResolveRequestRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type ResolveRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequestResponse) Reset() {
	*x = ResolveRequestResponse{}
	mi := &file_arda_capital_v1_capital_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequestResponse) ProtoMessage() {}

func (x *ResolveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_capital_v1_capital_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequestResponse.ProtoReflect.Descriptor instead.
func (*ResolveRequestResponse) Descriptor() ([]byte, []int) {
	return file_arda_capital_v1_capital_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveRequestResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_arda_capital_v1_capital_proto protoreflect.FileDescriptor

const file_arda_capital_v1_capital_proto_rawDesc = "" +
	"\n" +
	"\x1darda/capital/v1/capital.proto\x12\x0farda.capital.v1\"@\n" +
	"\x13CheckRequestRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x15\n" +
	"\x06ref_id\x18\x02 \x01(\tR\x05refId\"@\n" +
	"\x14CheckRequestResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\x15ResolveRequestRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x15\n" +
	"\x06ref_id\x18\x02 \x01(\tR\x05refId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\"(\n" +
	"\x16ResolveRequestResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xd7\x01\n" +
	"\x15CapitalCommandService\x12[\n" +
	"\fCheckRequest\x12$.arda.capital.v1.CheckRequestRequest\x1a%.arda.capital.v1.CheckRequestResponse\x12a\n" +
	"\x0eResolveRequest\x12&.arda.capital.v1.ResolveRequestRequest\x1a'.arda.capital.v1.ResolveRequestResponseBCZAgithub.com/arda-labs/arda/libs/go/arda-proto/capital/v1;capitalv1b\x06proto3"

var (
	file_arda_capital_v1_capital_proto_rawDescOnce sync.Once
	file_arda_capital_v1_capital_proto_rawDescData []byte
)

func file_arda_capital_v1_capital_proto_rawDescGZIP() []byte {
	file_arda_capital_v1_capital_proto_rawDescOnce.Do(func() {
		file_arda_capital_v1_capital_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arda_capital_v1_capital_proto_rawDesc), len(file_arda_capital_v1_capital_proto_rawDesc)))
	})
	return file_arda_capital_v1_capital_proto_rawDescData
}

var file_arda_capital_v1_capital_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_arda_capital_v1_capital_proto_goTypes = []any{
	(*CheckRequestRequest)(nil),    // 0: arda.capital.v1.CheckRequestRequest
	(*CheckRequestResponse)(nil),   // 1: arda.capital.v1.CheckRequestResponse
	(*ResolveRequestRequest)(nil),  // 2: arda.capital.v1.ResolveRequestRequest
	(*ResolveRequestResponse)(nil), // 3: arda.capital.v1.ResolveRequestResponse
}
var file_arda_capital_v1_capital_proto_depIdxs = []int32{
	0, // 0: arda.capital.v1.CapitalCommandService.CheckRequest:input_type -> arda.capital.v1.CheckRequestRequest
	2, // 1: arda.capital.v1.CapitalCommandService.ResolveRequest:input_type -> arda.capital.v1.ResolveRequestRequest
	1, // 2: arda.capital.v1.CapitalCommandService.CheckRequest:output_type -> arda.capital.v1.CheckRequestResponse
	3, // 3: arda.capital.v1.CapitalCommandService.ResolveRequest:output_type -> arda.capital.v1.ResolveRequestResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arda_capital_v1_capital_proto_init() }
func file_arda_capital_v1_capital_proto_init() {
	if File_arda_capital_v1_capital_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arda_capital_v1_capital_proto_rawDesc), len(file_arda_capital_v1_capital_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arda_capital_v1_capital_proto_goTypes,
		DependencyIndexes: file_arda_capital_v1_capital_proto_depIdxs,
		MessageInfos:      file_arda_capital_v1_capital_proto_msgTypes,
	}.Build()
	File_arda_capital_v1_capital_proto = out.File
	file_arda_capital_v1_capital_proto_goTypes = nil
	file_arda_capital_v1_capital_proto_depIdxs = nil
}
