// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: arda/hrm/v1/hrm.proto

package hrmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListIAMUsersByOrgUnitRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrgUnitId          string                 `protobuf:"bytes,1,opt,name=org_unit_id,json=orgUnitId,proto3" json:"org_unit_id,omitempty"`
	IncludeDescendants bool                   `protobuf:"varint,2,opt,name=include_descendants,json=includeDescendants,proto3" json:"include_descendants,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListIAMUsersByOrgUnitRequest) Reset() {
	*x = ListIAMUsersByOrgUnitRequest{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIAMUsersByOrgUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIAMUsersByOrgUnitRequest) ProtoMessage() {}

func (x *ListIAMUsersByOrgUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIAMUsersByOrgUnitRequest.ProtoReflect.Descriptor instead.
func (*ListIAMUsersByOrgUnitRequest) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{0}
}

func (x *ListIAMUsersByOrgUnitRequest) GetOrgUnitId() string {
	if x != nil {
		return x.OrgUnitId
	}
	return ""
}

func (x *ListIAMUsersByOrgUnitRequest) GetIncludeDescendants() bool {
	if x != nil {
		return x.IncludeDescendants
	}
	return false
}

type ListIAMUsersByOrgUnitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IamUserIds    []string               `protobuf:"bytes,1,rep,name=iam_user_ids,json=iamUserIds,proto3" json:"iam_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIAMUsersByOrgUnitResponse) Reset() {
	*x = ListIAMUsersByOrgUnitResponse{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIAMUsersByOrgUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIAMUsersByOrgUnitResponse) ProtoMessage() {}

func (x *ListIAMUsersByOrgUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIAMUsersByOrgUnitResponse.ProtoReflect.Descriptor instead.
func (*ListIAMUsersByOrgUnitResponse) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{1}
}

func (x *ListIAMUsersByOrgUnitResponse) GetIamUserIds() []string {
	if x != nil {
		return x.IamUserIds
	}
	return nil
}

type CheckRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckRegistrationRequest) Reset() {
	*x = CheckRegistrationRequest{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegistrationRequest) ProtoMessage() {}

func (x *CheckRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CheckRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRegistrationRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type CheckRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegistrationResponse) Reset() {
	*x = CheckRegistrationResponse{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegistrationResponse) ProtoMessage() {}

func (x *CheckRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CheckRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{3}
}

func (x *CheckRegistrationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SettleRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	ApprovedBy     string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SettleRegistrationRequest) Reset() {
	*x = SettleRegistrationRequest{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRegistrationRequest) ProtoMessage() {}

func (x *SettleRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRegistrationRequest.ProtoReflect.Descriptor instead.
func (*SettleRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{4}
}

func (x *SettleRegistrationRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *SettleRegistrationRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type SettleRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	EmployeeId    string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRegistrationResponse) Reset() {
	*x = SettleRegistrationResponse{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRegistrationResponse) ProtoMessage() {}

func (x *SettleRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRegistrationResponse.ProtoReflect.Descriptor instead.
func (*SettleRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{5}
}

func (x *SettleRegistrationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SettleRegistrationResponse) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type RejectRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	DecidedBy      string                 `protobuf:"bytes,2,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	Note           string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RejectRegistrationRequest) Reset() {
	*x = RejectRegistrationRequest{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRegistrationRequest) ProtoMessage() {}

func (x *RejectRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRegistrationRequest.ProtoReflect.Descriptor instead.
func (*RejectRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{6}
}

func (x *RejectRegistrationRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *RejectRegistrationRequest) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

func (x *RejectRegistrationRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RejectRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRegistrationResponse) Reset() {
	*x = RejectRegistrationResponse{}
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRegistrationResponse) ProtoMessage() {}

func (x *RejectRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arda_hrm_v1_hrm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRegistrationResponse.ProtoReflect.Descriptor instead.
func (*RejectRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_arda_hrm_v1_hrm_proto_rawDescGZIP(), []int{7}
}

func (x *RejectRegistrationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_arda_hrm_v1_hrm_proto protoreflect.FileDescriptor

const file_arda_hrm_v1_hrm_proto_rawDesc = "" +
	"\n" +
	"\x15arda/hrm/v1/hrm.proto\x12\varda.hrm.v1\"o\n" +
	"\x1cListIAMUsersByOrgUnitRequest\x12\x1e\n" +
	"\vorg_unit_id\x18\x01 \x01(\tR\torgUnitId\x12/\n" +
	"\x13include_descendants\x18\x02 \x01(\bR\x12includeDescendants\"A\n" +
	"\x1dListIAMUsersByOrgUnitResponse\x12 \n" +
	"\fiam_user_ids\x18\x01 \x03(\tR\n" +
	"iamUserIds\"C\n" +
	"\x18CheckRegistrationRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\"E\n" +
	"\x19CheckRegistrationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\x19SettleRegistrationRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy\"M\n" +
	"\x1aSettleRegistrationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\"w\n" +
	"\x19RejectRegistrationRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x1d\n" +
	"\n" +
	"decided_by\x18\x02 \x01(\tR\tdecidedBy\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\",\n" +
	"\x1aRejectRegistrationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xba\x03\n" +
	"\x16EmployeeCommandService\x12b\n" +
	"\x11CheckRegistration\x12%.arda.hrm.v1.CheckRegistrationRequest\x1a&.arda.hrm.v1.CheckRegistrationResponse\x12e\n" +
	"\x12SettleRegistration\x12&.arda.hrm.v1.SettleRegistrationRequest\x1a'.arda.hrm.v1.SettleRegistrationResponse\x12e\n" +
	"\x12RejectRegistration\x12&.arda.hrm.v1.RejectRegistrationRequest\x1a'.arda.hrm.v1.RejectRegistrationResponse\x12n\n" +
	"\x15ListIAMUsersByOrgUnit\x12).arda.hrm.v1.ListIAMUsersByOrgUnitRequest\x1a*.arda.hrm.v1.ListIAMUsersByOrgUnitResponseB;Z9github.com/arda-labs/arda/libs/go/arda-proto/hrm/v1;hrmv1b\x06proto3"

var (
	file_arda_hrm_v1_hrm_proto_rawDescOnce sync.Once
	file_arda_hrm_v1_hrm_proto_rawDescData []byte
)

func file_arda_hrm_v1_hrm_proto_rawDescGZIP() []byte {
	file_arda_hrm_v1_hrm_proto_rawDescOnce.Do(func() {
		file_arda_hrm_v1_hrm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arda_hrm_v1_hrm_proto_rawDesc), len(file_arda_hrm_v1_hrm_proto_rawDesc)))
	})
	return file_arda_hrm_v1_hrm_proto_rawDescData
}

var file_arda_hrm_v1_hrm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_arda_hrm_v1_hrm_proto_goTypes = []any{
	(*ListIAMUsersByOrgUnitRequest)(nil),  // 0: arda.hrm.v1.ListIAMUsersByOrgUnitRequest
	(*ListIAMUsersByOrgUnitResponse)(nil), // 1: arda.hrm.v1.ListIAMUsersByOrgUnitResponse
	(*CheckRegistrationRequest)(nil),      // 2: arda.hrm.v1.CheckRegistrationRequest
	(*CheckRegistrationResponse)(nil),     // 3: arda.hrm.v1.CheckRegistrationResponse
	(*SettleRegistrationRequest)(nil),     // 4: arda.hrm.v1.SettleRegistrationRequest
	(*SettleRegistrationResponse)(nil),    // 5: arda.hrm.v1.SettleRegistrationResponse
	(*RejectRegistrationRequest)(nil),     // 6: arda.hrm.v1.RejectRegistrationRequest
	(*RejectRegistrationResponse)(nil),    // 7: arda.hrm.v1.RejectRegistrationResponse
}
var file_arda_hrm_v1_hrm_proto_depIdxs = []int32{
	2, // 0: arda.hrm.v1.EmployeeCommandService.CheckRegistration:input_type -> arda.hrm.v1.CheckRegistrationRequest
	4, // 1: arda.hrm.v1.EmployeeCommandService.SettleRegistration:input_type -> arda.hrm.v1.SettleRegistrationRequest
	6, // 2: arda.hrm.v1.EmployeeCommandService.RejectRegistration:input_type -> arda.hrm.v1.RejectRegistrationRequest
	0, // 3: arda.hrm.v1.EmployeeCommandService.ListIAMUsersByOrgUnit:input_type -> arda.hrm.v1.ListIAMUsersByOrgUnitRequest
	3, // 4: arda.hrm.v1.EmployeeCommandService.CheckRegistration:output_type -> arda.hrm.v1.CheckRegistrationResponse
	5, // 5: arda.hrm.v1.EmployeeCommandService.SettleRegistration:output_type -> arda.hrm.v1.SettleRegistrationResponse
	7, // 6: arda.hrm.v1.EmployeeCommandService.RejectRegistration:output_type -> arda.hrm.v1.RejectRegistrationResponse
	1, // 7: arda.hrm.v1.EmployeeCommandService.ListIAMUsersByOrgUnit:output_type -> arda.hrm.v1.ListIAMUsersByOrgUnitResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arda_hrm_v1_hrm_proto_init() }
func file_arda_hrm_v1_hrm_proto_init() {
	if File_arda_hrm_v1_hrm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arda_hrm_v1_hrm_proto_rawDesc), len(file_arda_hrm_v1_hrm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arda_hrm_v1_hrm_proto_goTypes,
		DependencyIndexes: file_arda_hrm_v1_hrm_proto_depIdxs,
		MessageInfos:      file_arda_hrm_v1_hrm_proto_msgTypes,
	}.Build()
	File_arda_hrm_v1_hrm_proto = out.File
	file_arda_hrm_v1_hrm_proto_goTypes = nil
	file_arda_hrm_v1_hrm_proto_depIdxs = nil
}
