// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: arda/hrm/v1/hrm.proto

package hrmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmployeeCommandService_CheckRegistration_FullMethodName  = "/arda.hrm.v1.EmployeeCommandService/CheckRegistration"
	EmployeeCommandService_SettleRegistration_FullMethodName = "/arda.hrm.v1.EmployeeCommandService/SettleRegistration"
	EmployeeCommandService_RejectRegistration_FullMethodName = "/arda.hrm.v1.EmployeeCommandService/RejectRegistration"
)

// EmployeeCommandServiceClient is the client API for EmployeeCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmployeeCommandService is the callback surface workflow-service workers
// use to execute HRM employee-registration steps (mirror of crm
// CustomerCommandService). Tenant scope arrives via gRPC metadata.
type EmployeeCommandServiceClient interface {
	CheckRegistration(ctx context.Context, in *CheckRegistrationRequest, opts ...grpc.CallOption) (*CheckRegistrationResponse, error)
	SettleRegistration(ctx context.Context, in *SettleRegistrationRequest, opts ...grpc.CallOption) (*SettleRegistrationResponse, error)
	RejectRegistration(ctx context.Context, in *RejectRegistrationRequest, opts ...grpc.CallOption) (*RejectRegistrationResponse, error)
}

type employeeCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeCommandServiceClient(cc grpc.ClientConnInterface) EmployeeCommandServiceClient {
	return &employeeCommandServiceClient{cc}
}

func (c *employeeCommandServiceClient) CheckRegistration(ctx context.Context, in *CheckRegistrationRequest, opts ...grpc.CallOption) (*CheckRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRegistrationResponse)
	err := c.cc.Invoke(ctx, EmployeeCommandService_CheckRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeCommandServiceClient) SettleRegistration(ctx context.Context, in *SettleRegistrationRequest, opts ...grpc.CallOption) (*SettleRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleRegistrationResponse)
	err := c.cc.Invoke(ctx, EmployeeCommandService_SettleRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeCommandServiceClient) RejectRegistration(ctx context.Context, in *RejectRegistrationRequest, opts ...grpc.CallOption) (*RejectRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectRegistrationResponse)
	err := c.cc.Invoke(ctx, EmployeeCommandService_RejectRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeCommandServiceServer is the server API for EmployeeCommandService service.
// All implementations must embed UnimplementedEmployeeCommandServiceServer
// for forward compatibility.
//
// EmployeeCommandService is the callback surface workflow-service workers
// use to execute HRM employee-registration steps (mirror of crm
// CustomerCommandService). Tenant scope arrives via gRPC metadata.
type EmployeeCommandServiceServer interface {
	CheckRegistration(context.Context, *CheckRegistrationRequest) (*CheckRegistrationResponse, error)
	SettleRegistration(context.Context, *SettleRegistrationRequest) (*SettleRegistrationResponse, error)
	RejectRegistration(context.Context, *RejectRegistrationRequest) (*RejectRegistrationResponse, error)
	mustEmbedUnimplementedEmployeeCommandServiceServer()
}

// UnimplementedEmployeeCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployeeCommandServiceServer struct{}

func (UnimplementedEmployeeCommandServiceServer) CheckRegistration(context.Context, *CheckRegistrationRequest) (*CheckRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRegistration not implemented")
}
func (UnimplementedEmployeeCommandServiceServer) SettleRegistration(context.Context, *SettleRegistrationRequest) (*SettleRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleRegistration not implemented")
}
func (UnimplementedEmployeeCommandServiceServer) RejectRegistration(context.Context, *RejectRegistrationRequest) (*RejectRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectRegistration not implemented")
}
func (UnimplementedEmployeeCommandServiceServer) mustEmbedUnimplementedEmployeeCommandServiceServer() {
}
func (UnimplementedEmployeeCommandServiceServer) testEmbeddedByValue() {}

// UnsafeEmployeeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeCommandServiceServer will
// result in compilation errors.
type UnsafeEmployeeCommandServiceServer interface {
	mustEmbedUnimplementedEmployeeCommandServiceServer()
}

func RegisterEmployeeCommandServiceServer(s grpc.ServiceRegistrar, srv EmployeeCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedEmployeeCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmployeeCommandService_ServiceDesc, srv)
}

func _EmployeeCommandService_CheckRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeCommandServiceServer).CheckRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeCommandService_CheckRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeCommandServiceServer).CheckRegistration(ctx, req.(*CheckRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeCommandService_SettleRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeCommandServiceServer).SettleRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeCommandService_SettleRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeCommandServiceServer).SettleRegistration(ctx, req.(*SettleRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeCommandService_RejectRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeCommandServiceServer).RejectRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeCommandService_RejectRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeCommandServiceServer).RejectRegistration(ctx, req.(*RejectRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeCommandService_ServiceDesc is the grpc.ServiceDesc for EmployeeCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arda.hrm.v1.EmployeeCommandService",
	HandlerType: (*EmployeeCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRegistration",
			Handler:    _EmployeeCommandService_CheckRegistration_Handler,
		},
		{
			MethodName: "SettleRegistration",
			Handler:    _EmployeeCommandService_SettleRegistration_Handler,
		},
		{
			MethodName: "RejectRegistration",
			Handler:    _EmployeeCommandService_RejectRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arda/hrm/v1/hrm.proto",
}
